Repository EdgeTX/edgetx, pull requests merged in 2023-04, with the labels that each got.

#3420 DA translation bug corrected
  radio/src/translations/da.h
Labels: translation, bug/regression ↩️

#3422 fix(color) - Adjust portrait layout for debug view.
  radio/src/gui/colorlcd/view_statistics.cpp
Labels: color, UX-UI

#3426 fix (cpn): fw simulator crashes on loading MPM protocol list
  radio/src/gui/gui_common.cpp
Labels: bug/regression ↩️

#3437 Win64 Companion build, fix for "Cannot handle non anonymous unions" exception
  radio/util/generate_datacopy.py
Labels: compilation

#3419 fix: X10access - no PPM output on CPPM pin
  radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp
Labels: bug/regression ↩️

#3417 fix(color) - Fix issue where top menu bar still active when widget popup menu is opened
  radio/src/gui/colorlcd/widget.cpp
Labels: bug 🪲, color

#3433 feat(color) - Show the 'Press any key to skip' message on alerts that currently have no message.
  radio/src/opentx.h
  radio/src/storage/sdcard_common.cpp
Labels: enhancement ✨, color

#3338 feat(radio) - Add 'repeat' option to 'Lua Script' special function.
  companion/src/firmwares/customfunctiondata.cpp
  companion/src/firmwares/customfunctiondata.h
  companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
  companion/src/modeledit/customfunctions.cpp
  companion/src/modeledit/customfunctions.h
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/colorlcd/special_functions.cpp
  radio/src/lua/interface.cpp
  radio/src/myeeprom.h
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Labels: enhancement ✨, color, B&W, companion

#3315 Add layout 4+2B right side 3QRT+1QRT
  companion/src/companion.qrc
  companion/src/firmwares/customisation_data.h
  companion/src/images/layouts/mask_layout4+2b.png
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/layouts/layout4+2b.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
Labels: enhancement ✨, color, widget

#3447 Update fr.h
  radio/src/translations/fr.h
Labels: translation

#3459 fix(radio) - Fix crash when editing multi module type on 212x64 LCD B&W radios.
  radio/src/gui/212x64/model_setup.cpp
Labels: bug 🪲, B&W, simulator

#3444 fix: undesired MPM protocol selection changes
  radio/src/storage/storage_common.cpp
Labels: bug/regression ↩️

#3452 fix(X9lite): Chan. monitor, other display glitches
  radio/src/gui/128x64/model_failsafe.cpp
  radio/src/gui/128x64/widgets.cpp
  radio/src/gui/common/stdlcd/model_receiver_options.cpp
Labels: bug 🪲, B&W

#3463 fix(color) - Fix for custom failsafe settings not being saved to SD card on color LCD radios.
  radio/src/gui/colorlcd/custom_failsafe.cpp
Labels: bug 🪲, color

#3465 Fixed EL18 failsafe only have 4 channels functioning
  radio/src/pulses/afhds3.cpp
Labels: bug 🪲

#3471 (v2.8.3 Telemetry fix) Bring Spektrum Telemetry Changes from main to 2.8 branch (GPS+TextGen)
  radio/src/telemetry/spektrum.cpp
Labels: bug 🪲, telemetry

#2764 Work out a dynamic splash screen that fits all screen sizes.
  radio/src/bitmaps/480x272/CMakeLists.txt
  radio/src/bitmaps/480x272/mask_splash_bg.png
  radio/src/bitmaps/480x272/splash_bg.png
  radio/src/bitmaps/480x272/splash_bg2.png
  radio/src/bitmaps/480x272/splash_logo.png
  radio/src/gui/colorlcd/splash.cpp
Labels: color

#3460 chore(color) - Fix TX16S firmware build when DEBUG=YES and INTERNAL_MODULE_PXX2=OFF.
  radio/src/cli.cpp
Labels: compilation

#3453 fix(color) - Fix memory leak when disconnecting USB in SD card mode.
  radio/src/gui/colorlcd/themes/480_default.cpp
Labels: bug 🪲, color

#3442 Fix configurable port, solved R9M Access problem and support FRM303 via mod
  radio/src/hal/module_port.cpp
  radio/src/pulses/afhds3.cpp
  radio/src/pulses/pulses.cpp
  radio/src/serial.cpp
  radio/src/targets/horus/CMakeLists.txt
Labels: enhancement ✨, bug/regression ↩️

#3476 feat(color) - Sort the widget list by display name.
  radio/src/gui/colorlcd/widget.cpp
Labels: enhancement ✨, color

#3478 feat(color) Add haptic startup buzz for radios with no startup animation
  radio/src/opentx.cpp
Labels: enhancement ✨

#3441 fix(color): Rework rotary encoder acceleration calculation removing double handling
  radio/src/gui/colorlcd/LvglWrapper.cpp
Labels: bug 🪲, color

#3445 fix(radio) - Fix direction detection for rotary encoder on startup.
  radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
Labels: bug 🪲

#3439 fix(color) - Fix issue where popup telemetry warning can crash radio.
  radio/src/gui/colorlcd/popups.cpp
  radio/src/gui/colorlcd/popups.h
  radio/src/gui/common/stdlcd/popups.h
  radio/src/main.cpp
  radio/src/telemetry/telemetry.cpp
Labels: bug 🪲, color

#3485 Update it.h
  radio/src/translations/it.h
Labels: translation

#3401 feat(color,cpn) - Updates to the model telemetry page.
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  companion/src/firmwares/edgetx/yaml_sensordata.cpp
  companion/src/firmwares/modeldata.h
  companion/src/modeledit/telemetry.cpp
  companion/src/modeledit/telemetry.ui
  companion/src/multimodelprinter.cpp
  companion/src/simulation/telemetrysimu.cpp
  radio/src/datastructs_private.h
  radio/src/gui/128x64/model_telemetry_sensor.cpp
  radio/src/gui/212x64/model_telemetry_sensor.cpp
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/gui/colorlcd/model_telemetry.h
  radio/src/storage/yaml/yaml_datastructs_boxer.cpp
  radio/src/storage/yaml/yaml_datastructs_lr3pro.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_t12.cpp
  radio/src/storage/yaml/yaml_datastructs_t8.cpp
  radio/src/storage/yaml/yaml_datastructs_tlite.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_tx12.cpp
  radio/src/storage/yaml/yaml_datastructs_tx12mk2.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x7.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lites.cpp
  radio/src/storage/yaml/yaml_datastructs_xlite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/storage/yaml/yaml_datastructs_zorro.cpp
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: color, UX-UI, translation

#3472 fix CPN: LUA no debug printout possible
  radio/src/thirdparty/Lua/src/luaconf.h
Labels: simulator, bug/regression ↩️

#3479 fix(color): Scroll order for 'FlySky' module options
  radio/src/gui/colorlcd/flysky_settings.cpp
  radio/src/gui/colorlcd/flysky_settings.h
  radio/src/hal/module_port.h
  radio/src/pulses/afhds3.cpp
  radio/src/pulses/afhds3_transport.cpp
Labels: color, bug/regression ↩️

#3494 (v2.8) Added symbol \u5b57 to CN/TW font conversion
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_17.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_17.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_17.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_17.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/fonts/lvgl/make_fonts.sh
Labels: bug 🪲, color

#3329 fix: corrupt data using soft serial driver
  radio/src/mixer_scheduler.h
  radio/src/targets/common/arm/stm32/heartbeat_driver.cpp
  radio/src/targets/common/arm/stm32/mixer_scheduler_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/taranis/hal.h
Labels: bug/regression ↩️

#3489 Added symbol \u5b57 to CN/TW font conversion.
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_17.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_17.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_17.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_17.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/fonts/lvgl/make_fonts.sh
Labels: bug 🪲, color

#3293 fix(radio) - Announce timer value as hours and minutes when played from special function.
  radio/src/translations/tts_cn.cpp
  radio/src/translations/tts_cz.cpp
  radio/src/translations/tts_da.cpp
  radio/src/translations/tts_de.cpp
  radio/src/translations/tts_en.cpp
  radio/src/translations/tts_es.cpp
  radio/src/translations/tts_fr.cpp
  radio/src/translations/tts_hu.cpp
  radio/src/translations/tts_it.cpp
  radio/src/translations/tts_nl.cpp
  radio/src/translations/tts_pl.cpp
  radio/src/translations/tts_pt.cpp
  radio/src/translations/tts_ru.cpp
  radio/src/translations/tts_se.cpp
  radio/src/translations/tts_sk.cpp
Labels: bug 🪲

#3400 feat(radio,cpn) - Updates for new joystick system.
  companion/src/apppreferencesdialog.cpp
  companion/src/simulation/joystick.cpp
  companion/src/simulation/joystick.h
  companion/src/simulation/joystickdialog.cpp
  companion/src/simulation/joystickdialog.h
  companion/src/simulation/simulatorwidget.cpp
  companion/src/storage/appdata.cpp
  companion/src/storage/appdata.h
  radio/src/datastructs_private.h
  radio/src/usb_joystick.cpp
Labels: enhancement ✨, companion

#3510 fix: Building TX16s firmware with -DDEBUG=YES -DCMAKE_BUILD_TYPE=Debug fails
  radio/src/serial.cpp
Labels: compilation, bug/regression ↩️

#3520 fix(color) - Fix '!1x' repeat option broken in PR 3338.
  radio/src/gui/colorlcd/special_functions.cpp
Labels: color, bug/regression ↩️

#3516 chore: add basic stuff for LSP (clangd)
  .gitignore
  cmake/GenericDefinitions.cmake
Labels: compilation
