Repository EdgeTX/edgetx, pull requests merged in 2023-09, with the labels that each got.

#3941 fix: PXX1 external module timings
  radio/src/boards/generic_stm32/module_ports.cpp
  radio/src/targets/common/arm/stm32/stm32_softserial_driver.cpp
  radio/src/targets/common/arm/stm32/stm32_softserial_driver.h
Labels: bug/regression ↩️

#3973 Enable LUA_MIXER, hidden by default
  radio/src/CMakeLists.txt
  radio/src/model_init.cpp
  radio/src/opentx.cpp
  radio/src/storage/sdcard_common.cpp
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/nv14/CMakeLists.txt
Labels: compilation

#3840 feat(cpn): Identify new and changed models by italicising row
  companion/src/firmwares/modeldata.h
  companion/src/mdichild.cpp
  companion/src/mdichild.h
  companion/src/modelslist.cpp
Labels: enhancement ✨, companion

#3971 feat(cpn): Only show active channels in source lists
  companion/src/firmwares/rawsource.cpp
  companion/src/modeledit/mixes.cpp
  companion/src/modeledit/mixes.h
Labels: enhancement ✨, companion

#3989 chore(b&w): Reduce FLASH storage used by 212x64 startup/shutdown animations.
  radio/src/bitmaps/212x64/lock.png
  radio/src/bitmaps/212x64/power.png
  radio/src/bitmaps/212x64/shutdown.png
  radio/src/gui/212x64/lcd.cpp
  radio/src/gui/212x64/lcd.h
  radio/src/gui/212x64/startup_shutdown.cpp
Labels: enhancement ✨, compilation

#3930 fix(cpn): custom function filename length
  companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
Labels: bug 🪲, companion

#4001 chore(color): Remove unused color bitmap images
  radio/src/bitmaps/480x272/default_theme/mask_iconback.png
  radio/src/bitmaps/480x272/default_theme/mask_opentx.png
  radio/src/bitmaps/480x272/default_theme/mask_opentx_testmode.png
  radio/src/bitmaps/480x272/default_theme/mask_question.png
  radio/src/bitmaps/480x272/default_theme/thumb.png
  radio/src/bitmaps/480x272/mask_about_headico.png
  radio/src/bitmaps/480x272/mask_carroussel_left.png
  radio/src/bitmaps/480x272/mask_carroussel_right.png
  radio/src/bitmaps/480x272/mask_dropdown.png
  radio/src/bitmaps/480x272/mask_folder.png
  radio/src/bitmaps/480x272/mask_htrim_frame.png
  radio/src/bitmaps/480x272/mask_key_backspace.png
  radio/src/bitmaps/480x272/mask_key_letters.png
  radio/src/bitmaps/480x272/mask_key_lowercase.png
  radio/src/bitmaps/480x272/mask_key_numbers.png
  radio/src/bitmaps/480x272/mask_key_spacebar.png
  radio/src/bitmaps/480x272/mask_key_uppercase.png
  radio/src/bitmaps/480x272/mask_library_active_model.png
  radio/src/bitmaps/480x272/mask_library_score_0.png
  radio/src/bitmaps/480x272/mask_library_score_1.png
  radio/src/bitmaps/480x272/mask_library_slot.png
  radio/src/bitmaps/480x272/mask_library_star_0.png
  radio/src/bitmaps/480x272/mask_library_star_1.png
  radio/src/bitmaps/480x272/mask_mainviews_item_in.png
  radio/src/bitmaps/480x272/mask_mainviews_item_out.png
  radio/src/bitmaps/480x272/mask_splash_bg.png
  radio/src/bitmaps/480x272/mask_swipe_circle.png
  radio/src/bitmaps/480x272/mask_swipe_left.png
  radio/src/bitmaps/480x272/mask_swipe_right.png
  radio/src/bitmaps/480x272/mask_topmenu_altitude_ico.png
  radio/src/bitmaps/480x272/mask_topmenu_masterpart_ico.png
  radio/src/bitmaps/480x272/mask_topmenu_sdcard.png
  radio/src/bitmaps/480x272/mask_topmenu_slavepart_ico.png
  radio/src/bitmaps/480x272/mask_topmenu_volume_ico.png
  radio/src/bitmaps/480x272/mask_vtrim_frame.png
  radio/src/bitmaps/480x272/slider/bar_left.png
  radio/src/bitmaps/480x272/slider/bar_right.png
  radio/src/bitmaps/480x272/slider/point_in.png
  radio/src/bitmaps/480x272/slider/point_mid.png
  radio/src/bitmaps/480x272/slider/point_out.png
  radio/src/bitmaps/480x272/splash_bg2.png
  radio/src/gui/colorlcd/splash.cpp
Labels: compilation

#3981 enh(cpn): trainer modes more closely minmic firmware
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  companion/src/firmwares/modeldata.cpp
  companion/src/firmwares/modeldata.h
  companion/src/modeledit/setup.cpp
  companion/src/modeledit/setup.h
Labels: enhancement ✨, companion

#4020 Translate for danish
  companion/src/translations/companion_da.ts
  radio/src/translations/da.h
Labels: translation

#3783 chores(flysky): separate AFHDS2A and AFHDS3 into 2 different module type
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/CMakeLists.txt
  companion/src/firmwares/CMakeLists.txt
  companion/src/firmwares/afhds3.cpp
  companion/src/firmwares/afhds3.h
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/edgetx/yaml_moduledata.cpp
  companion/src/firmwares/moduledata.cpp
  companion/src/firmwares/moduledata.h
  companion/src/firmwares/opentx/opentxeeprom.cpp
  companion/src/firmwares/opentx/opentxeeprom.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/modeledit/setup.cpp
  companion/src/modeledit/setup_module.ui
  companion/src/modelprinter.cpp
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetEL18.cpp
  companion/src/simulation/simulateduiwidgetEL18.ui
  companion/src/simulation/simulatorwidget.cpp
  fw.json
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/CMakeLists.txt
  radio/src/gui/colorlcd/afhds2a_settings.cpp
  radio/src/gui/colorlcd/afhds2a_settings.h
  radio/src/gui/colorlcd/afhds3_settings.cpp
  radio/src/gui/colorlcd/afhds3_settings.h
  radio/src/gui/colorlcd/channel_range.cpp
  radio/src/gui/colorlcd/module_setup.cpp
  radio/src/gui/gui_common.cpp
  radio/src/pulses/modules_constants.h
  radio/src/pulses/modules_helpers.h
  radio/src/pulses/pulses.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/nv14/board.h
  radio/src/telemetry/telemetry.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/untranslated.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-flysky.py
  tools/build-gh.sh
  tools/commit-tests.sh
Labels: color, B&W, companion

#3887 feat(radio): Delay warnings until after splash screen finished
  radio/src/opentx.cpp
  radio/src/tasks.cpp
Labels: enhancement ✨

#3848 fix(cpn): selection of sound packs in update process
  companion/src/updates/chooserdialog.cpp
  companion/src/updates/chooserdialog.h
  companion/src/updates/chooserdialog.ui
  companion/src/updates/updateinterface.cpp
  companion/src/updates/updateinterface.h
  companion/src/updates/updatesounds.cpp
  companion/src/updates/updatesounds.h
  companion/src/updates/updatestatus.cpp
Labels: companion, rn: warning, bug/regression ↩️

#3762 fix(color): Fix handling of blank lines in YAML files.
  radio/src/storage/yaml/yaml_parser.cpp
  radio/src/tests/yaml.cpp
Labels: bug/regression ↩️

#4040 fix: compile error if X9D and USE_RTC_CLOCK=OFF
  radio/src/gui/212x64/radio_setup.cpp
Labels: compilation

#4035 fix: T18 has no power switch on AUX2
  radio/src/targets/horus/hal.h
Labels: bug 🪲

#4058 chore(radio): Fix some compiler warnings when building firmware
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/gui/colorlcd/radio_diagkeys.cpp
  radio/src/gui/colorlcd/radio_sdmanager.cpp
  radio/src/gui/colorlcd/view_text.cpp
  radio/src/gui/common/stdlcd/radio_sdmanager.cpp
  radio/src/lua/interface.cpp
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/targets/common/arm/stm32/f4/system_stm32f4xx.c
  radio/src/telemetry/multi.cpp
Labels: compilation

#4071 fix(color): Detect changes to telemetry sensors that return strings
  radio/src/telemetry/telemetry_sensors.cpp
Labels: bug 🪲, color

#4075 chore(radio): Cleanup TRACE output for AFHDS3 module.
  radio/src/pulses/afhds3.cpp
  radio/src/pulses/afhds3_transport.cpp
Labels: simulator, compilation

#4005 fix: use SWRC_NONE if switch cannot be found
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Labels: bug 🪲

#4013 chore(color): Cleanup EdgeTxTheme class.
  companion/src/firmwares/customisation_data.cpp
  companion/src/firmwares/customisation_data.h
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/firmwares/opentx/opentxeeprom.cpp
  companion/src/modeledit/colorcustomscreens.cpp
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/curve.cpp
  radio/src/gui/colorlcd/draw_functions.cpp
  radio/src/gui/colorlcd/fab_button.cpp
  radio/src/gui/colorlcd/fullscreen_dialog.cpp
  radio/src/gui/colorlcd/gui.h
  radio/src/gui/colorlcd/layout.cpp
  radio/src/gui/colorlcd/layout.h
  radio/src/gui/colorlcd/layouts/layout_factory_impl.h
  radio/src/gui/colorlcd/layouts/topbar_impl.cpp
  radio/src/gui/colorlcd/page.cpp
  radio/src/gui/colorlcd/tabsgroup.cpp
  radio/src/gui/colorlcd/theme.cpp
  radio/src/gui/colorlcd/theme.h
  radio/src/gui/colorlcd/theme_manager.cpp
  radio/src/gui/colorlcd/themes/480_default.cpp
  radio/src/gui/colorlcd/view_main.cpp
  radio/src/gui/colorlcd/widget.cpp
  radio/src/gui/colorlcd/widgets/radio_info.cpp
  radio/src/lua/api_colorlcd.cpp
  radio/src/main.cpp
  radio/src/myeeprom.h
  radio/src/opentx.cpp
  radio/src/storage/sdcard_common.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/thirdparty/libopenui/src/libopenui_defines.h
Labels: compilation

#3903 feat(color): Add information bubble popup window.
  radio/src/gui/colorlcd/popups.cpp
  radio/src/gui/colorlcd/popups.h
  radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
  radio/src/thirdparty/libopenui/src/mainwindow.cpp
  radio/src/thirdparty/libopenui/src/widgets/etx_obj_create.h
  radio/src/thirdparty/libopenui/src/window.h
Labels: enhancement ✨, color

#4081 chore(radio): Use existing 'hash' function for detecting settings change in USB joystick
  radio/src/usb_joystick.cpp
Labels: house keeping 🧹

#4078 fix(color): Update background color on user interface page when theme is changed.
  radio/src/gui/colorlcd/screen_user_interface.cpp
  radio/src/gui/colorlcd/screen_user_interface.h
Labels: bug 🪲, color

#3986 feat: enable S.PORT telemetry by default for SBUS and PPM modules
  radio/src/pulses/ppm.cpp
  radio/src/pulses/sbus.cpp
Labels: bug/regression ↩️

#4084 fix(color): Ensure all items are updated on theme change in user interface settings.
  radio/src/gui/colorlcd/screen_user_interface.cpp
Labels: bug 🪲, color

#4091 fix(color): Fix the popup menu entries when selecting the value for the Trainer special function.
  radio/src/gui/colorlcd/special_functions.cpp
Labels: color, bug/regression ↩️

#4092 chore(color): Remove unused code from 'About EdgeTX' popup.
  radio/src/gui/colorlcd/view_about.cpp
  radio/src/gui/colorlcd/view_about.h
Labels: color, house keeping 🧹

#4055 fix(color): Fixes for switch and source select popup menus.
  radio/src/gui/colorlcd/sourcechoice.cpp
  radio/src/gui/colorlcd/switchchoice.cpp
  radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
  radio/src/targets/horus/libopenui_config.h
  radio/src/targets/nv14/libopenui_config.h
  radio/src/thirdparty/libopenui/src/choice.cpp
  radio/src/thirdparty/libopenui/src/menutoolbar.cpp
  radio/src/thirdparty/libopenui/src/menutoolbar.h
Labels: bug 🪲, enhancement ✨, color

#4085 fix: prevent enabling USART IRQ if not supported
  radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
Labels: bug 🪲

#4086 fix: prevent enabling USART IRQ if not supported
  radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
Labels: bug 🪲

#3987 fix(color): Allow scrolling of the version info dialog popup with the rotary encoder wheel.
  radio/src/gui/colorlcd/radio_version.cpp
Labels: bug 🪲, color

#3988 fix(color): Reverse direction of color shutdown animation.
  radio/src/gui/colorlcd/draw_functions.cpp
Labels: color, UX-UI

#4087 fix: inaccurate Batt measurement on T20
  radio/src/targets/taranis/board.h
Labels: rn: warning, partner

#3953 feat(color): Show custom image during shutdown if present
  radio/src/gui/colorlcd/draw_functions.cpp
  radio/src/sdcard.h
Labels: enhancement ✨, color, UX-UI

#4096 fix(radio): Fix size of fields on sensor edit page for portrait layout
  radio/src/gui/colorlcd/model_telemetry.cpp
Labels: color, UX-UI

#3999 fix: better iteration through mixers on display
  radio/src/CMakeLists.txt
  radio/src/gui/128x64/gui.h
  radio/src/gui/128x64/model_mix_edit.cpp
  radio/src/gui/212x64/gui.h
  radio/src/gui/212x64/model_mix_edit.cpp
  radio/src/gui/colorlcd/menus.h
  radio/src/gui/colorlcd/mixer_edit.cpp
  radio/src/gui/colorlcd/mixer_edit_adv.cpp
  radio/src/gui/colorlcd/model_mixes.cpp
  radio/src/gui/common/stdlcd/model_mixes.cpp
  radio/src/gui/gui_common.cpp
  radio/src/lua/api_model.cpp
  radio/src/mixer.cpp
  radio/src/mixes.cpp
  radio/src/mixes.h
  radio/src/model_init.cpp
  radio/src/opentx.cpp
  radio/src/opentx.h
  radio/src/storage/storage_common.cpp
Labels: bug 🪲

#4024 fix: Deactivate logs and close log file if USB is connected
  radio/src/logs.cpp
Labels: bug 🪲

#4103 fix: ADC DMA clock enable and inhibit mask for internal channels
  radio/src/targets/common/arm/stm32/stm32_adc.cpp
Labels: bug 🪲

#3574 feat(color): Add alignment option for text widget
  radio/src/gui/colorlcd/widgets/text.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/tw.h
Labels: enhancement ✨, color, widget

#4108 fix: VS1053b initialisation on NV14/EL18
  radio/src/targets/common/arm/stm32/vs1053b.cpp
Labels: bug/regression ↩️

#4080 fix(ibus): Separate lat long sensors merged to single GPS sensor
  radio/src/telemetry/flysky_ibus.cpp
Labels: bug 🪲, telemetry

#4113 fix: ifdef in some translations
  radio/src/translations/cn.h
  radio/src/translations/he.h
  radio/src/translations/jp.h
  radio/src/translations/tw.h
Labels: translation, compilation, bug/regression ↩️

#4047 fix: USART IRQ priority for external module
  radio/src/boards/generic_stm32/module_ports.cpp
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
Labels: bug 🪲, telemetry

#4065 fix: GitPod container image now needs their workspace image as base
  .github/workflows/actions.yml
  .gitpod.yml
  radio/src/CMakeLists.txt
Labels: bug 🪲

#4117 fix: align BT defines for Zorro on other radios
  radio/src/targets/taranis/CMakeLists.txt
Labels: bug 🪲

#4110 fix(color): Make toggle switch UI consistent with other UI elements
  radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
Labels: color, UX-UI

#4129 fix(radio): Lua insertMix function not working
  radio/src/lua/api_model.cpp
  radio/src/mixes.cpp
Labels: bug/regression ↩️

#3996 fix(b&w): Fix radio UI display for switches on X9D, X9D+ and X9D+2019.
  radio/util/hw_defs/switch_config.py
Labels: bug/regression ↩️

#4026 chore(translation): Russian translation updates for Companion
  companion/src/translations/companion_ru.ts
Labels: companion, translation

#4141 fix(translation): Missing " for IT translation
  radio/src/translations/it.h
Labels: bug 🪲, translation
