Repository EdgeTX/edgetx, pull requests merged in 2023-07, with the labels that each got.

#3718 Jumper TPro V2
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  fw.json
  radio/src/datastructs.h
  radio/src/gui/128x64/radio_diagkeys.cpp
  radio/src/opentx.cpp
  radio/src/opentx.h
  radio/src/simu.cpp
  radio/src/stamp.cpp
  radio/src/storage/yaml/yaml_datastructs.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
  radio/src/telemetry/crossfire.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-gh.sh
  tools/generate-hw-defs.sh
Labels: hardware support

#3734 Fix missing Discover telemetry line missing
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/212x64/model_telemetry.cpp
Labels: bug/regression ↩️

#3735 feat(cpn): User configurable audio mute in radio settings
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/hardware.cpp
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
Labels: companion

#3733 Fix thottle timer
  radio/src/mixer.cpp
  radio/src/opentx.cpp
  radio/src/switches.cpp
Labels: bug/regression ↩️

#3742 fix(radio) - Fix timer unit announcements.
  radio/src/audio.cpp
  radio/src/dataconstants.h
Labels: bug/regression ↩️

#3750 Allow compile without multimodule support
  radio/src/gui/gui_common.h
  radio/src/targets/common/arm/CMakeLists.txt
  radio/src/telemetry/frsky_defs.h
  radio/src/telemetry/spektrum.cpp
  radio/src/telemetry/telemetry.cpp
  radio/src/telemetry/telemetry_sensors.cpp
Labels: compilation

#3755 fix: SD Logs interval shown as default value when entering SF edit window
  radio/src/gui/colorlcd/special_functions.cpp
Labels: color, bug/regression ↩️

#3743 Fix centerbeep on 212 display
  radio/src/gui/212x64/model_setup.cpp
  radio/util/hw_defs/legacy_names.py
Labels: bug/regression ↩️

#3747 fix(color): Names and number of buttons on Preflight checks screen
  radio/src/gui/colorlcd/preflight_checks.cpp
Labels: bug/regression ↩️

#3769 chore: Fix build when GVARS=NO
  radio/src/gui/colorlcd/gvar_numberedit.cpp
Labels: bug 🪲, compilation

#3767 chore: Comment out the top two trace flooding calls
  radio/src/targets/horus/diskio.cpp
  radio/src/targets/horus/lcd_driver.cpp
  radio/src/targets/nv14/diskio.cpp
Labels: compilation

#3770 feat(bw): Change layout of telemetry page on B&W radios to match color layout (alternative way)
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/212x64/model_telemetry.cpp
  radio/src/gui/gui_common.cpp
  radio/src/gui/gui_common.h
Labels: B&W

#3786 fix(Lua): Enable 'package' Lua library.
  radio/src/thirdparty/Lua/src/linit.c
Labels: color, lua-api, bug/regression ↩️

#3763 fix: reset proto scan software timer to MULTI_PROTOLIST_START_TIMEOUT
  radio/src/io/multi_protolist.cpp
Labels: bug 🪲

#3785 fix(color): Fix inputs and mixes scroll order
  radio/src/gui/colorlcd/model_inputs.cpp
  radio/src/gui/colorlcd/model_mixes.cpp
Labels: color, bug/regression ↩️

#3754 Add X7S BT detection
  radio/src/opentx.cpp
  radio/src/targets/common/arm/stm32/bluetooth_driver.cpp
  radio/src/targets/simu/bt_driver.cpp
Labels: bug/regression ↩️

#3789 fix: TLite V2 is using another MCU
  radio/src/opentx.cpp
Labels: hardware support

#3775 JSON Python generator docs
  radio/util/hw_defs/README.md
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
Labels: documentation

#3741 Feature: SF Audio amplifier mute - 2.9 edition
  companion/src/firmwares/customfunctiondata.cpp
  companion/src/firmwares/customfunctiondata.h
  companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
  radio/src/dataconstants.h
  radio/src/functions.cpp
  radio/src/storage/yaml/yaml_datastructs_boxer.cpp
  radio/src/storage/yaml/yaml_datastructs_lr3pro.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_t8.cpp
  radio/src/storage/yaml/yaml_datastructs_tlite.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_tx12.cpp
  radio/src/storage/yaml/yaml_datastructs_tx12mk2.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_zorro.cpp
  radio/src/targets/common/arm/stm32/audio_dac_driver.cpp
  radio/src/targets/nv14/audio_spi_driver.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: enhancement ✨

#3797 chore: Move gt911 touch to generic EXTI driver
  radio/src/targets/common/arm/stm32/stm32_exti_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/horus/tp_gt911.cpp
Labels: compilation

#3790 chore: clean hal (phase 1 of many)
  radio/src/boards/generic_stm32/aux_ports.cpp
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
  radio/src/targets/horus/board.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/nv14/board.cpp
  radio/src/targets/nv14/hal.h
  radio/src/targets/taranis/board.cpp
  radio/src/targets/taranis/hal.h
Labels: compilation

#3624 Rationalise module size handling
  radio/src/gui/gui_common.cpp
  radio/src/targets/common/arm/CMakeLists.txt
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/hal.h
Labels: enhancement ✨

#3628 feat(cpn): External module form factor set in Radio Profile to allow aligning with firmware compile option
  companion/src/apppreferencesdialog.cpp
  companion/src/apppreferencesdialog.ui
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/moduledata.cpp
  companion/src/mainwindow.cpp
  companion/src/modeledit/setup.cpp
  companion/src/storage/appdata.h
Labels: enhancement ✨, companion, rn: warning

#3406 feat(radio,cpn): Support all current timezones.
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/CMakeLists.txt
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
  companion/src/generaledit/timezoneedit.cpp
  companion/src/generaledit/timezoneedit.h
  companion/src/thirdparty/maxlibqt/src/widgets/TimerEdit.h
  radio/src/datastructs_private.h
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/rtc.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/strhelpers.cpp
  radio/src/strhelpers.h
  radio/src/telemetry/spektrum.cpp
Labels: enhancement ✨

#3637 Remove MPM no telemetry GUI on non FrSky radio
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/colorlcd/mpm_settings.cpp
  radio/src/gui/gui_common.h
Labels: enhancement ✨

#3819 fix(color): Fix crash in MPM settings from PR #3637
  radio/src/gui/colorlcd/mpm_settings.cpp
  radio/src/gui/colorlcd/mpm_settings.h
Labels: color, bug/regression ↩️

#3825 fix(cpn): reduce curve name length to match firmware
  companion/src/firmwares/curvedata.h
Labels: bug 🪲, companion

#3824 chore(cpn): disable backup and restore for all radios
  companion/src/mainwindow.cpp
Labels: companion

#3766 feat(cpn): warn if radio settings version not supported
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
Labels: enhancement ✨, companion

#3826 chore(build): Add missing source for bootloader debug build.
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
Labels: compilation, bug/regression ↩️

#3576 safeguard RTC backup memory
  radio/src/opentx.cpp
  radio/src/rtc.h
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
  radio/src/targets/common/arm/stm32/rtc_driver.cpp
  radio/src/targets/horus/board.cpp
  radio/src/targets/horus/board.h
  radio/src/targets/nv14/board.cpp
  radio/src/targets/nv14/board.h
Labels: enhancement ✨

#3839 fix(cpn): add missing module types to module size lists
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/moduledata.cpp
Labels: companion, bug/regression ↩️

#3831 fix: revert Zorro default contrast
  radio/src/opentx.cpp
  radio/src/targets/taranis/board.h
Labels: bug 🪲, B&W

#3828 feat: auto expand sensor list when discovering sensors
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/212x64/model_telemetry.cpp
Labels: enhancement ✨, B&W

#3845 fix(color): Change behaviour of TELE button on widget setup page to work like RTN button.
  radio/src/gui/colorlcd/widgets_setup.cpp
Labels: bug 🪲, color

#3779 fix(el18): switch ADC channel and direction
  radio/src/targets/nv14/hal.h
Labels: bug/regression ↩️

#3731 Companion simulator pots and sliders adc refactor fixes
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  companion/src/helpers.cpp
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/targets/simu/simpgmspace.cpp
Labels: companion, simulator, bug/regression ↩️

#3857 fix(x-lite): ADC channel definition
  radio/src/targets/taranis/hal.h
Labels: bug/regression ↩️

#3863 fix: pot types strings
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: bug/regression ↩️

#3855 fix(color): Expand analog diagnostic page to full height
  radio/src/gui/colorlcd/radio_diaganas.cpp
Labels: bug 🪲, color, touch

#3868 feat: Default audio mute on for RM radios
  radio/src/opentx.cpp
Labels: partner

#3827 Fix french and Czech translations for BW radios
  radio/src/fonts/sqt5/font_cz_04x06.png
  radio/src/fonts/sqt5/font_cz_05x07.png
  radio/src/fonts/sqt5/font_cz_08x10.png
  radio/src/fonts/sqt5/font_cz_10x14.png
  radio/src/fonts/std/font_cz_04x06.png
  radio/src/fonts/std/font_cz_05x07.png
  radio/src/fonts/std/font_cz_08x10.png
  radio/src/fonts/std/font_cz_10x14.png
  radio/src/gui/common/stdlcd/utf8.cpp
  radio/src/translations/fr.h
Labels: B&W, translation

#3832 fix(b&w): Font related fixes for B&W radios.
  radio/src/fonts/sqt5/font_05x07_extra.png
  radio/src/fonts/std/font_05x07_extra.png
  radio/src/translations/cz.h
Labels: bug 🪲, B&W

#3856 feat(128): Swap modelname for timer1 if defined
  radio/src/gui/128x64/lcd.cpp
Labels: UX-UI, B&W

#3796 PT Language revision
  radio/src/translations/pt.h
Labels: translation

#3451 feat(radio,cpn): Startup splash screen and sound changes.
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
  radio/src/datastructs_private.h
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/opentx.cpp
  radio/src/opentx.h
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/tasks.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/tw.h
  radio/src/translations/untranslated.h
Labels: bug 🪲, enhancement ✨, color

#3875 fix(color): Fix switch selection when physical switch moved in Flight Mode edit page.
  radio/src/gui/colorlcd/model_flightmodes.cpp
Labels: color, bug/regression ↩️

#3803 fix(lua): add missing switch constants
  radio/src/lua/CMakeLists.txt
  radio/src/lua/api_general.cpp
  radio/src/tests/lua.cpp
  radio/util/hw_defs/lua_mixsrc.jinja
Labels: lua, bug/regression ↩️

#3860 fix: use keysGetMaxTrims() instead of MAX_TRIMS
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/colorlcd/model_flightmodes.cpp
  radio/src/gui/colorlcd/radio_diagkeys.cpp
  radio/src/keys.cpp
  radio/src/lua/api_model.cpp
  radio/src/mixer.cpp
  radio/src/opentx.cpp
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
  radio/src/targets/simu/simpgmspace.cpp
  radio/src/targets/taranis/hal.h
  radio/util/hw_defs/hal_keys.py
  radio/util/hw_defs/json_index.py
  radio/util/hw_defs/stm32_keys.jinja
Labels: bug/regression ↩️

#3864 fix: throttle invert and gimbal dead zone
  radio/src/mixer.cpp
  radio/src/tests/mixer.cpp
Labels: bug/regression ↩️

#3884 chore(color): Remove duplicate TR_SF_TEST entries from translation files.
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: compilation

#3871 fix: Add remaining/elapsed display on BW telem topbar
  radio/src/gui/128x64/lcd.cpp
  radio/src/gui/212x64/lcd.cpp
Labels: UX-UI, B&W

#3879 fix: translation for timer mode
  radio/src/translations/fr.h
Labels: translation
