Repository EdgeTX/edgetx, pull requests merged in 2023-12, with the labels that each got.

#4372 chore(radio): Updates to Russian translations
  radio/src/translations/ru.h
Labels: translation

#3601 feat: Add "Enable" button to all SF/GF (#3024)
  companion/src/firmwares/customfunctiondata.cpp
  companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
  companion/src/modeledit/customfunctions.cpp
  radio/src/datastructs_private.h
  radio/src/functions.cpp
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/colorlcd/special_functions.cpp
  radio/src/lua/interface.cpp
  radio/src/myeeprom.h
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/thirdparty/libopenui/.clang-format
  radio/src/thirdparty/libopenui/.gitignore
  radio/src/thirdparty/libopenui/.gitmodules
  radio/src/thirdparty/libopenui/.idea/codeStyles/Project.xml
  radio/src/thirdparty/libopenui/.idea/codeStyles/codeStyleConfig.xml
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: enhancement ✨

#4375 chore(color): Update fonts
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
Labels: translation

#4382 perf(color): Remove multiple checks for model notes in quick menu
  radio/src/gui/colorlcd/view_main_menu.cpp
Labels: color

#4378 fix(color): Incorrect focus selection in GVAR list
  radio/src/gui/colorlcd/model_flightmodes.cpp
  radio/src/gui/colorlcd/model_gvars.cpp
Labels: bug 🪲, color, UX-UI

#4373 chore(cpn): Increase number of profiles that can be created
  companion/src/apppreferencesdialog.cpp
  companion/src/apppreferencesdialog.ui
  companion/src/mainwindow.cpp
  companion/src/storage/appdata.cpp
  companion/src/storage/appdata.h
Labels: companion

#4384 fix(cpn): PL18 simulator layout.
  companion/src/images/simulator/PL18/bottom.png
  companion/src/images/simulator/PL18/left.png
  companion/src/images/simulator/PL18/right.png
  companion/src/images/simulator/PL18/top.png
  companion/src/simulation/simulateduiwidgetPL18.ui
Labels: simulator

#4387 chore: Remove unused LCD_DUAL_BUFFER
  radio/src/gui/212x64/lcd.cpp
  radio/src/gui/212x64/lcd.h
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
Labels: B&W, compilation, house keeping 🧹

#4392 fix(bw128): Show first 4 trims when radio has > 4 trims
  radio/src/gui/128x64/view_main.cpp
Labels: bug 🪲, B&W

#4394 fix(color): Initialisation of Lua widget options
  radio/src/lua/widgets.cpp
Labels: bug 🪲, color, widget, lua

#4390 fix(color): Wrong input could be used for updating curve preview
  radio/src/gui/colorlcd/input_edit.cpp
  radio/src/gui/colorlcd/input_edit.h
  radio/src/gui/colorlcd/mixer_edit.cpp
  radio/src/gui/colorlcd/mixer_edit.h
Labels: bug 🪲, color, UX-UI

#4366 feat(color): Compress font data with LZ4
  radio/src/fonts/lvgl/lv_font_arimo_he_13.c
  radio/src/fonts/lvgl/lv_font_arimo_he_24.c
  radio/src/fonts/lvgl/lv_font_arimo_he_9.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_64.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_13.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_24.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_9.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_64.c
  radio/src/fonts/lvgl/lv_font_roboto_13.c
  radio/src/fonts/lvgl/lv_font_roboto_24.c
  radio/src/fonts/lvgl/lv_font_roboto_9.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_16.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_32.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_64.c
  radio/src/fonts/lvgl/lz4_font.cpp
  radio/src/fonts/lvgl/make_fonts.sh
  radio/src/gui/colorlcd/fonts.cpp
  radio/src/gui/colorlcd/lz4_fonts.h
  radio/src/lv_conf.h
  radio/src/thirdparty/libopenui/thirdparty/lz4/lz4.c
  radio/src/thirdparty/libopenui/thirdparty/lz4/lz4.h
  radio/src/thirdparty/libopenui/thirdparty/lz4/lz4hc.c
  radio/src/thirdparty/libopenui/thirdparty/lz4/lz4hc.h
Labels: color

#4402 fix(b&w): Top left '!' warning always flashing on B&W simulators
  radio/src/gui/128x64/view_main.cpp
  radio/src/gui/212x64/view_main.cpp
Labels: B&W, simulator

#4401 feat(bw): Add inverted edit option for rotary encoder
  companion/src/generaledit/generalsetup.cpp
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/navigation/navigation_x7.cpp
  radio/src/gui/navigation/navigation_x9d.cpp
  radio/src/opentx.h
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: B&W

#4395 fix(color): Trim display inconsistent with B&W
  radio/src/gui/colorlcd/layouts/trims.cpp
Labels: bug 🪲, color, UX-UI

#4400 fix(ws2812): Bit order of WS2812 data stream
  radio/src/targets/common/arm/stm32/stm32_ws2812.cpp
Labels: bug 🪲

#4359 feat(nv14/el18): Add help popup showing mapping when using hats as keys.
  radio/src/gui/colorlcd/message_dialog.cpp
  radio/src/gui/colorlcd/message_dialog.h
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/gui/colorlcd/trims_setup.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: color, UX-UI

#4408 chore(color): Change STR_CAL to STR_CALIBRATION on trainer page
  radio/src/gui/colorlcd/radio_trainer.cpp
Labels: color, UX-UI

#4409 chore: allow native companion compilation on linux
  companion/src/CMakeLists.txt
Labels: companion, compilation

#4413 fix: default channel order should be ST
  radio/src/opentx.cpp
Labels: bug 🪲

#4414 chore: Updated SE translations
  companion/src/translations/companion_sv.ts
  radio/src/translations/se.h
Labels: translation

#4291 chore: improve finding Homebrew's Qt5 on macOS
  cmake/QtDefs.cmake
Labels: compilation, house keeping 🧹

#4418 fix(pl18): Fixed LCD detection code
  radio/src/targets/pl18/lcd_driver.cpp
  radio/src/targets/pl18/lcd_driver.h
Labels: bug 🪲

#4396 chore: Use the CMake way for linker options
  radio/src/CMakeLists.txt
  radio/src/boards/generic_stm32/linker/stm32f429_sdram/layout.ld
  radio/src/targets/common/arm/stm32/CMakeLists.txt
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
  radio/src/targets/common/arm/stm32/f2/CMakeLists.txt
  radio/src/targets/common/arm/stm32/f4/CMakeLists.txt
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/pl18/CMakeLists.txt
Labels: bug 🪲, compilation

#4420 chore(translation): CZ "Manage Models"
  radio/src/translations/cz.h
Labels: translation

#4426 fix(radio): Radio YAML file not being read or written correctly.
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
Labels: bug/regression ↩️

#4405 fix(b&w): Various rotenc. inversion bugs on radio and simu
  companion/src/simulation/simulateduiwidgetBoxer.cpp
  radio/src/gui/common/stdlcd/popups.cpp
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: bug 🪲, UX-UI, B&W, simulator

#4419 chore(color): Turn off LVGL compression of font data.
  radio/src/fonts/lvgl/lv_font_arimo_he_13.c
  radio/src/fonts/lvgl/lv_font_arimo_he_24.c
  radio/src/fonts/lvgl/lv_font_arimo_he_9.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_64.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_13.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_24.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_9.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_64.c
  radio/src/fonts/lvgl/lv_font_roboto_13.c
  radio/src/fonts/lvgl/lv_font_roboto_24.c
  radio/src/fonts/lvgl/lv_font_roboto_9.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_16.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_32.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_64.c
  radio/src/fonts/lvgl/lz4_font.cpp
  radio/src/fonts/lvgl/make_fonts.sh
  radio/src/gui/colorlcd/fonts.cpp
  radio/src/gui/colorlcd/lz4_fonts.h
Labels: color

#4428 fix(color): Filter Unix/MacOS dot files from file chooser popup menu.
  radio/src/thirdparty/libopenui/src/filechoice.cpp
Labels: color, UX-UI

#4432 fix(soft-serial): timer toggle mode would skip first period
  radio/src/targets/common/arm/stm32/stm32_pulse_driver.cpp
Labels: bug/regression ↩️

#4434 fix(bw): Restart from bootloader on F4 targets
  radio/src/boards/generic_stm32/startup/startup_stm32f40_41xxx.s
Labels: bug 🪲, B&W

#4436 fix(bw): Uncleared reusable buffer in sdmanager
  radio/src/gui/common/stdlcd/radio_sdmanager.cpp
Labels: bug 🪲, B&W

#4433 fix(color): Put LCD buffers at start of SDRAM
  radio/src/boards/generic_stm32/linker/stm32f429_sdram/extra_sections.ld
  radio/src/definitions.h
  radio/src/fonts/lvgl/lv_font_arimo_he_13.c
  radio/src/fonts/lvgl/lv_font_arimo_he_24.c
  radio/src/fonts/lvgl/lv_font_arimo_he_9.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_he_bold_64.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_13.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_24.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_9.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_ru_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_64.c
  radio/src/fonts/lvgl/lv_font_roboto_13.c
  radio/src/fonts/lvgl/lv_font_roboto_24.c
  radio/src/fonts/lvgl/lv_font_roboto_9.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_16.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_32.c
  radio/src/fonts/lvgl/lv_font_roboto_bold_64.c
  radio/src/fonts/lvgl/lz4_font.cpp
Labels: color

#3923 chores(lua): generate keys definitions
  radio/src/lua/CMakeLists.txt
  radio/src/lua/api_general.cpp
  radio/util/hw_defs/lua_keys.jinja
Labels: needs: testing, lua

#4438 fix(cpn): Translation of GPS Run/Stop in telemetry simulator
  companion/src/simulation/telemetrysimu.cpp
  companion/src/translations/companion_sv.ts
Labels: bug 🪲, companion, translation

#4364 fix(radio): Mix delay not working.
  radio/src/globals.h
  radio/src/mixer.cpp
  radio/src/opentx.h
  radio/src/tests/gtests.h
  radio/src/tests/mixer.cpp
Labels: bug/regression ↩️

#4449 feat(bootloader): Don't show Unix/MacOS dotfiles in firmware list
  radio/src/targets/common/arm/stm32/bootloader/bin_files.cpp
Labels: UX-UI

#4445 chore(cpn): QtLinguist translation files refresh
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
Labels: companion

#4446 fix(bw): Cannot change the 'enabled' state for global functions
  radio/src/gui/128x64/menu_radio.cpp
  radio/src/gui/212x64/menu_radio.cpp
Labels: bug 🪲, B&W

#4447 fix(MT12): Incorrect scrolling in radio setup menu.
  radio/src/gui/128x64/radio_setup.cpp
Labels: bug 🪲

#4448 fix(MT12): Cannot properly edit pre-start check switch warning state on MT12.
  radio/src/gui/128x64/model_setup.cpp
Labels: bug 🪲

#4442 fix(telemetry): Inconsistent/wrong GPS distance calculation
  radio/src/telemetry/telemetry_sensors.cpp
  radio/src/telemetry/telemetry_sensors.h
Labels: telemetry 📶, bug/regression ↩️

#4450 fix: increase init repeat max time for slow(est) cards
  radio/src/targets/common/arm/stm32/sdcard_spi.cpp
Labels: bug 🪲

#4151 Allow Touch Screen Mod on Horus X10 Transmitters
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/horus/hal.h
Labels: hardware support, touch 👆

#4451 fix(cpn): 6-position translation for RU
  companion/src/translations/companion_ru.ts
Labels: bug 🪲, companion, translation

#4458 fix(bw): Progressive checklist `=` behaviour was reversed
  radio/src/gui/common/stdlcd/view_text.cpp
Labels: bug 🪲, B&W

#4471 fix(PL18/PL18EV): Broken USB functionalities post #4207
  radio/src/targets/common/arm/stm32/usbd_conf.c
Labels: bug/regression ↩️

#4482 feat(color): Make model sorting case insensitive
  radio/src/storage/modelslist.cpp
Labels: enhancement ✨, color, UX-UI

#4492 fix(vs1053b): Remove EarSpeaker Spatial Processing
  radio/src/targets/common/arm/stm32/vs1053b.cpp
Labels: bug 🪲, sound 🔉

#4491 fix(radio): Instant trim only works correctly in mode 1
  radio/src/opentx.cpp
Labels: bug/regression ↩️

#4476 fix(pl18): Audio playback hiccup problem when SPI flash is writing
  radio/src/audio.h
Labels: bug 🪲, sound 🔉
