Repository EdgeTX/edgetx, pull requests merged in 2024-02, with the labels that each got.

#4582 fix: MT12 T1/T2 reversed vs printout on radio
  radio/src/targets/taranis/hal.h
Labels: bug 🪲

#4579 chore(radio): Automate copyright year based on build date
  CMakeLists.txt
  companion/src/CMakeLists.txt
  radio/src/gui/128x64/view_about.cpp
  radio/src/gui/212x64/view_about.cpp
  radio/src/gui/colorlcd/view_about.cpp
  radio/src/stamp.h.in
Labels: compilation, house keeping 🧹

#4583 fix(telemetry): Correct A1..A2 voltage sensors value for Frsky_D/OMP
  radio/src/telemetry/frsky_d.cpp
Labels: telemetry 📶, bug/regression ↩️

#4592 chore(radio): Cleanup NV14 BT GPIO code
  radio/src/targets/nv14/board.h
  radio/src/targets/nv14/hal.h
  radio/src/targets/pl18/hal.h
Labels: house keeping 🧹

#4601 fix: restore master serial option
  radio/src/gui/gui_common.cpp
Labels: bug/regression ↩️

#4584 fix(cpn): Custom screens yaml being truncated
  companion/src/firmwares/customisation_data.cpp
  companion/src/firmwares/customisation_data.h
  companion/src/firmwares/opentx/opentxeeprom.cpp
Labels: bug 🪲, companion, house keeping 🧹

#4599 feat(cpn): add support for new 'Manage Models' settings
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
Labels: color, companion

#4604 Japanese: Correction of display defects identified in v2.9.3
  radio/src/translations/jp.h
Labels: translation

#4621 fix: load LUA SF after selection
  radio/src/gui/128x64/model_special_functions.cpp
Labels: bug 🪲, B&W

#4617 Update Danish translation
  companion/src/translations/companion_da.ts
  radio/src/translations/da.h
Labels: translation

#4620 fix: MT12 ghost trim entries
  radio/src/gui/128x64/model_flightmodes.cpp
Labels: B&W, bug/regression ↩️

#4623 fix(radio): Refresh Lua scripts if needed when SF/GF updated.
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/colorlcd/special_functions.cpp
Labels: bug 🪲

#4624 Update Japanese translations
  radio/src/translations/jp.h
Labels: translation

#4600 fix(telemetry): DSM/LemonRX sensor cleanup for Altimeter and Flight Pack Monitors
  radio/src/telemetry/spektrum.cpp
Labels: telemetry 📶

#4588 fix(radio): Delta Logical Switch functions may not work consistently for all sources.
  radio/src/switches.cpp
Labels: bug 🪲

#4612 feat(radio): Allow precision for mix slow up/dn to be set to 10ms or 100ms.
  companion/src/firmwares/edgetx/yaml_mixdata.cpp
  companion/src/firmwares/mixdata.h
  companion/src/modeledit/mixerdialog.cpp
  companion/src/modeledit/mixerdialog.ui
  companion/src/modelprinter.cpp
  radio/src/datastructs_private.h
  radio/src/gui/128x64/gui.h
  radio/src/gui/128x64/menu_model.cpp
  radio/src/gui/128x64/model_flightmodes.cpp
  radio/src/gui/128x64/model_mix_edit.cpp
  radio/src/gui/212x64/gui.h
  radio/src/gui/212x64/menu_model.cpp
  radio/src/gui/212x64/model_mix_edit.cpp
  radio/src/gui/colorlcd/mixer_edit_adv.cpp
  radio/src/gui/colorlcd/mixer_edit_adv.h
  radio/src/mixer.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/tests/mixer.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨

#4628 chore(cpn): use win32 dfu-util binary release
  .github/workflows/win_cpn-32.yml
Labels: companion, compilation

#4630 feat(lua): add support for CRSF 'direct command' packets
  radio/src/lua/api_general.cpp
Labels: lua-api

#4653 fix(radio): "DCL - The Game" not detecting USB joystick
  radio/src/targets/common/arm/stm32/usbd_desc.c
Labels: bug/regression ↩️

#4660 fix: Fixed grammatical errors in the :ukraine: translation
  radio/src/translations/ua.h
Labels: translation

#4674 fix(translation): harmonise TR_ENTER for PCBPL18
  radio/src/translations/da.h
  radio/src/translations/fi.h
  radio/src/translations/he.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
Labels: bug 🪲, translation

#4662 chore: updates to SE translations
  companion/src/translations/companion_sv.ts
  radio/src/translations/se.h
Labels: translation

#4675 fix(radio): memory leak in ModelMap::renameLabel
  radio/src/storage/modelslist.cpp
Labels: bug 🪲, color

#4671 fix: ignore invalid GVAR feature flag on BW128 UI
  radio/src/storage/storage_common.cpp
Labels: bug 🪲, B&W, blocks-release

#4668 Trainer: allow Master/SBUS Module mode on S.Port pin
  radio/src/gui/gui_common.cpp
  radio/src/hal/module_port.h
  radio/src/trainer.cpp
Labels: bug 🪲, enhancement ✨

#4641 fix(cpn): switches default types
  companion/src/firmwares/boardjson.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/edgetx/yaml_switchconfig.cpp
  companion/src/firmwares/generalsettings.cpp
Labels: companion, bug/regression ↩️

#4651 fix(color): Switch and source select popup may show buttons for empty groups.
  radio/src/thirdparty/libopenui/src/menutoolbar.cpp
Labels: bug 🪲, color, UX-UI

#4631 feat(color): Use case insensitive sorting for list of widget names.
  radio/src/gui/colorlcd/widget.cpp
Labels: bug 🪲, enhancement ✨, color, UX-UI

#4647 fix: halt T14 power up when USB connected
  radio/src/targets/taranis/board.cpp
Labels: bug 🪲

#4629 Update Japanese translation (Companion maintenance)
  companion/src/translations/companion_ja.ts
Labels: companion, translation

#4677 fix: T7/T8 yaml handling
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Labels: bug 🪲, blocks-release

#4644 fix(lua): serialRead is not limited to CLI
  radio/src/lua/api_general.cpp
Labels: bug 🪲, lua-api

#4654 chore(cpn): Align general settings naming to radio
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/ersky9x/ersky9xeeprom.cpp
  companion/src/firmwares/ersky9x/ersky9xeeprom.h
  companion/src/firmwares/generalsettings.h
  companion/src/firmwares/opentx/opentxeeprom.cpp
  companion/src/generaledit/generalsetup.cpp
Labels: companion, house keeping 🧹

#4679 fix(radio): limit CLI to USB-VCP
  radio/src/gui/gui_common.cpp
Labels: bug 🪲
