Repository EdgeTX/edgetx, pull requests merged in 2024-05, with the labels that each got.

#4951 fix(bw): analog debug page text overlap
  radio/src/gui/128x64/radio_diaganas.cpp
Labels: B&W

#4948 fix(bw): potential crash when editing USB advanced setup
  radio/src/gui/common/stdlcd/model_usbjoystick.cpp
Labels: B&W

#4942 fix: some cppcheck errors
  radio/src/gui/colorlcd/afhds2a_settings.cpp
  radio/src/lua/interface.cpp
Labels: compilation, house keeping 🧹

#4947 fix(color): last interactive checklist line not shown if EoF not newline
  radio/src/gui/colorlcd/view_text.cpp
Labels: bug 🪲

#4954 fix(color): ensure outputs widget channel width is odd for symmetrical display
  radio/src/gui/colorlcd/widgets/outputs.cpp
Labels: bug 🪲, color, UX-UI

#4930 chore(radio): actually use the defined USB joystick strings
  radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
Labels: bug 🪲

#4904 fix(usb): report correct version number (#4903)
  radio/src/targets/common/arm/stm32/usbd_desc.c
Labels: bug 🪲

#4934 fix(bw): 'keys' debug view update
  radio/src/bitmaps/sticks.xbm
  radio/src/gui/128x64/radio_diagkeys.cpp
Labels: B&W

#4959 fix(crash): crash in LibGUI widget in fullscreen mode.
  radio/src/thirdparty/libopenui/src/bitmapbuffer_draw_extra.cpp
Labels: color, bug/regression ↩️

#4960 feat: use only vario sensor for vario source
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/212x64/model_telemetry.cpp
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/gui/gui_common.cpp
  radio/src/gui/gui_common.h
Labels: enhancement ✨

#4962 fix(debug): don't initalise SP_AUX1 if not exist
  radio/src/targets/horus/board.cpp
  radio/src/targets/nv14/board.cpp
  radio/src/targets/nv14/board.h
  radio/src/targets/pl18/board.cpp
  radio/src/targets/pl18/board.h
  radio/src/targets/taranis/board.cpp
Labels: bug 🪲

#4875 fix(telemetry): wrong scaling after changing unit to rpm
  radio/src/telemetry/telemetry_sensors.cpp
Labels: telemetry 📶

#4963 feat(cpn): only use vario sensors for vario source
  companion/src/datamodels/compounditemmodels.cpp
  companion/src/firmwares/sensordata.cpp
  companion/src/firmwares/sensordata.h
  companion/src/modeledit/telemetry.cpp
Labels: enhancement ✨

#4967 fix(bw): editing names on 9x/xlite nav radios & popup menu using wrong keys/events
  radio/src/gui/navigation/common.cpp
  radio/src/keys.h
Labels: UX-UI, B&W, bug/regression ↩️

#4845 feat(color): add color options for radio info widget battery level indicator
  radio/src/gui/colorlcd/widgets/radio_info.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, color, needs:translation

#4970 feat: allow T20V2 internal ELRS max baud to go up to 5.25M
  radio/src/telemetry/crossfire.h
Labels: hardware support, partner

#4968 fix(cpn): missing telem unit strings
  companion/src/firmwares/sensordata.cpp
Labels: bug 🪲, companion

#4971 chore(color): RU translation for Radio Info widget.
  radio/src/translations/ru.h
Labels: translation

#4976 fix(bw): adjust 128x64 layout to accommodate long switch names
  radio/src/gui/128x64/view_main.cpp
Labels: UX-UI, B&W

#4981 chore: updates for UA
  radio/src/translations/ua.h
Labels: translation

#4980 chore: missed check for Pocket ModelData size
  radio/src/datastructs.h
Labels: compilation, house keeping 🧹

#4831 feat: add ability to disable trainer warning on shutdown
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/opentx.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, UX-UI, needs:translation

#4988 feat: compile option to disable MCU check
  radio/src/CMakeLists.txt
  radio/src/opentx.cpp
Labels: compilation

#4991 fix(bw): bootloader not working with F407xG targets and > 512kb fw
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
Labels: bug 🪲, B&W

#4993 fix: replace non-compliant translations with EN ASCII
  radio/src/translations/he.h
  radio/src/translations/jp.h
  radio/src/translations/ru.h
  radio/src/translations/ua.h
Labels: translation, bug/regression ↩️

#5002 fix(bw212): wrong source string display
  radio/src/gui/212x64/lcd.cpp
Labels: B&W, bug/regression ↩️

#4997 fix(bw): use small switch layout when more than 6 switches
  radio/src/gui/128x64/view_main.cpp
Labels: B&W, bug/regression ↩️

#4936 chore: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, house keeping 🧹

#5022 fix(fw): compilation without AUDIO
  radio/src/audio.h
  radio/src/buzzer.h
  radio/src/cli.cpp
  radio/src/functions.cpp
  radio/src/globals.h
  radio/src/gui/128x64/view_statistics.cpp
  radio/src/gui/212x64/view_statistics.cpp
  radio/src/gui/colorlcd/view_statistics.cpp
  radio/src/gui/colorlcd/widgets/radio_info.cpp
  radio/src/main.cpp
  radio/src/mixer.cpp
  radio/src/opentx.cpp
  radio/src/tasks.cpp
  radio/src/tasks.h
Labels: house keeping 🧹

#5021 fix(fw): compilation without power switch
  radio/src/targets/common/arm/stm32/pwr_driver.cpp
Labels: house keeping 🧹

#4843 chore(radio): update FatFs to R0.15
  radio/src/hal/fatfs_diskio.cpp
  radio/src/rtos.h
  radio/src/targets/simu/simufatfs.cpp
  radio/src/thirdparty/FatFs/00history.txt
  radio/src/thirdparty/FatFs/00readme.txt
  radio/src/thirdparty/FatFs/LICENSE.txt
  radio/src/thirdparty/FatFs/diskio.h
  radio/src/thirdparty/FatFs/ff.c
  radio/src/thirdparty/FatFs/ff.h
  radio/src/thirdparty/FatFs/ffconf.h
  radio/src/thirdparty/FatFs/ffunicode.c
Labels: house keeping 🧹

#5012 fix(x9e): missing F3/F4 pots, slider hwdef changes
  companion/src/firmwares/generalsettings.cpp
  companion/src/firmwares/opentx/opentxeeprom.cpp
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
Labels: B&W, hardware support, bug/regression ↩️

#4757 chore(radio): stm32_mw_usb_device v2.11.2 catchup
  radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CompositeBuilder/Inc/usbd_composite_builder.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CompositeBuilder/Src/usbd_composite_builder.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Inc/usbd_customhid.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid_if_template.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_data.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_scsi.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Inc/usbd_core.h
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_core.c
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
Labels: house keeping 🧹

#5040 fix: Jumper T12 switches
  radio/util/hw_defs/switch_config.py
Labels: bug/regression ↩️

#5039 feat: improve debug handling
  radio/src/CMakeLists.txt
  radio/src/targets/common/arm/stm32/usb_driver.cpp
Labels: enhancement ✨, compilation

#5041 fix: improved debug handling, take 2
  radio/src/CMakeLists.txt
Labels: bug 🪲, enhancement ✨, compilation

#5042 feat: add debug for SDIO switch from 1bit to 4bits
  radio/src/targets/common/arm/stm32/diskio_sdio.cpp
Labels: enhancement ✨

#5048 fix(color): selected label, model list not correctly updating in single select mode
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/gui/colorlcd/model_select.h
Labels: bug 🪲, color

#5049 fix(color): selected label, model list not correctly updating in single select mode
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/gui/colorlcd/model_select.h
Labels: bug 🪲, color

#5037 fix(cpn): ensure hardware definitions are loaded when reading binary files
  companion/src/firmwares/opentx/opentxinterface.cpp
Labels: companion, bug/regression ↩️

#5047 fix(pxx2): prevent unnecessary model yaml rewrite on load
  radio/src/storage/storage_common.cpp
Labels: house keeping 🧹

#5026 fix(cpn): set input and switch types to none if not configured
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/edgetx/yaml_switchconfig.cpp
  companion/src/firmwares/generalsettings.cpp
Labels: companion, bug/regression ↩️

#5058 fix: add missing t20v2 simulator
  tools/build-companion.sh
Labels: bug 🪲, companion

#5060 chore: fix ci typo, remove redundant CPU_TYPE
  .github/workflows/actions.yml
  radio/src/targets/taranis/CMakeLists.txt
Labels: house keeping 🧹

#5019 fix(trainer): use the timer passed as argument
  radio/src/targets/common/arm/stm32/trainer_driver.cpp
Labels: house keeping 🧹

#5020 fix(fw): enable SYSCFG clock before using EXTI
  radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
Labels: house keeping 🧹

#4893 chore: auto define navigation type based on keys
  radio/src/gui/CMakeLists.txt
  radio/src/gui/navigation/navigation.cpp
  radio/src/opentx.h
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
Labels: house keeping 🧹

#5072 fix(cpn): global functions yaml decode
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
Labels: companion, bug/regression ↩️

#5075 fix(color): stop attempt to load themes when in emergency mode
  radio/src/gui/colorlcd/theme_manager.cpp
Labels: bug 🪲, color

#5073 fix(color): adjust layout of model labels list to reduce text overlap
  radio/src/gui/colorlcd/listbox.cpp
  radio/src/gui/colorlcd/listbox.h
  radio/src/gui/colorlcd/model_select.cpp
Labels: color, UX-UI, bug/regression ↩️

#5079 fix(cpn): validate translated update component name when used for folder name
  companion/src/updates/updateinterface.cpp
  companion/src/updates/updateinterface.h
Labels: bug 🪲, companion

#4649 feat(radio): modify Sensor Edit screens to show Ratio + Percentage
  radio/src/gui/128x64/model_telemetry_sensor.cpp
  radio/src/gui/212x64/model_telemetry_sensor.cpp
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/strhelpers.cpp
  radio/src/strhelpers.h
Labels: enhancement ✨, UX-UI

#5081 fix(color): adjust layout of model labels list to reduce text overlap
  radio/src/gui/colorlcd/listbox.cpp
  radio/src/gui/colorlcd/listbox.h
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
Labels: bug 🪲, color, UX-UI

#4883 fix(radio): properly center analog USB joystick axis
  radio/src/targets/common/arm/stm32/usb_driver.cpp
  radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
  radio/src/usb_joystick.cpp
Labels: bug 🪲

#5082 fix(bw): incorrect navigation in advanced USB setup on X9 radios
  radio/src/gui/common/stdlcd/model_usbjoystick.cpp
Labels: bug 🪲

#5086 fix: failing DEBUG simulator build for radios without customisable switches
  radio/src/gui/colorlcd/radio_diagcustswitches.cpp
Labels: compilation

#5067 fix(radio): correct different B&W and colorlcd trainer slave UI behaviour
  radio/src/gui/colorlcd/radio_trainer.cpp
  radio/src/translations/cn.h
  radio/src/translations/da.h
  radio/src/translations/en.h
  radio/src/translations/he.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/ua.h
Labels: bug 🪲, house keeping 🧹

#4655 feat(color): widget app mode
  radio/src/gui/colorlcd/layouts/layout_factory_impl.h
  radio/src/gui/colorlcd/layouts/topbar_impl.cpp
  radio/src/gui/colorlcd/layouts/topbar_impl.h
  radio/src/gui/colorlcd/theme.cpp
  radio/src/gui/colorlcd/theme.h
  radio/src/gui/colorlcd/view_main.cpp
  radio/src/gui/colorlcd/view_main.h
  radio/src/gui/colorlcd/widget.cpp
  radio/src/gui/colorlcd/widget.h
  radio/src/gui/colorlcd/widgets_setup.cpp
Labels: enhancement ✨, color, UX-UI, widget

#4946 feat(color): add filters to file chooser popup menu
  radio/src/gui/colorlcd/model_mixer_scripts.cpp
  radio/src/gui/colorlcd/model_setup.cpp
  radio/src/gui/colorlcd/special_functions.cpp
  radio/src/thirdparty/libopenui/src/choice.h
  radio/src/thirdparty/libopenui/src/filechoice.cpp
  radio/src/thirdparty/libopenui/src/filechoice.h
  radio/src/thirdparty/libopenui/src/menutoolbar.cpp
  radio/src/thirdparty/libopenui/src/menutoolbar.h
Labels: enhancement ✨, color, UX-UI, rn: feature

#4939 chore(bw): tidy up Radio Setup menu
  radio/src/gui/128x64/gui.h
  radio/src/gui/128x64/lcd.cpp
  radio/src/gui/128x64/lcd.h
  radio/src/gui/128x64/menu_model.cpp
  radio/src/gui/128x64/model_curve_edit.cpp
  radio/src/gui/128x64/model_flightmodes.cpp
  radio/src/gui/128x64/model_mix_edit.cpp
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/128x64/model_telemetry_sensor.cpp
  radio/src/gui/128x64/radio_diagkeys.cpp
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/128x64/view_telemetry.cpp
  radio/src/gui/128x64/widgets.cpp
  radio/src/gui/212x64/gui.h
  radio/src/gui/212x64/lcd.cpp
  radio/src/gui/212x64/lcd.h
  radio/src/gui/212x64/menu_model.cpp
  radio/src/gui/212x64/model_curve_edit.cpp
  radio/src/gui/212x64/model_display.cpp
  radio/src/gui/212x64/model_flightmodes.cpp
  radio/src/gui/212x64/model_input_edit.cpp
  radio/src/gui/212x64/model_mix_edit.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/212x64/model_telemetry.cpp
  radio/src/gui/212x64/model_telemetry_sensor.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/212x64/view_telemetry.cpp
  radio/src/gui/212x64/widgets.cpp
  radio/src/gui/common/stdlcd/CMakeLists.txt
  radio/src/gui/common/stdlcd/calibration.cpp
  radio/src/gui/common/stdlcd/draw_functions.cpp
  radio/src/gui/common/stdlcd/model_heli.cpp
  radio/src/gui/common/stdlcd/radio_hardware.cpp
  radio/src/gui/common/stdlcd/radio_version.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
  radio/util/fwoptions.py
Labels: B&W, house keeping 🧹

#4376 Logs: reset telemetry sensor data to inital state if telemetry is not streaming
  radio/src/logs.cpp
Labels: telemetry 📶

#5090 fix(bw): unresponsive rotary encoder after using popup menu on LS page
  radio/src/gui/128x64/model_logical_switches.cpp
Labels: B&W, bug/regression ↩️
