Repository EdgeTX/edgetx, pull requests merged in 2024-07, with the labels that each got.

#5236 fix: supported internal module for monochrome radios w/ ISRM
  radio/src/targets/taranis/CMakeLists.txt
Labels: bug 🪲

#5237 fix(el18): restore direct drawing capability for battery charging display
  radio/src/gui/colorlcd/lcd.cpp
Labels: color, bug/regression ↩️

#5240 fix: NV14/EL18 S.PORT TX DMA handler
  radio/src/targets/nv14/hal.h
Labels: bug/regression ↩️

#5244 fix(bw): incorrect X-Lite navigation selection
  radio/src/gui/navigation/navigation.cpp
  radio/src/opentx.h
Labels: B&W, bug/regression ↩️

#5247 fix(color): built in widgets do not resize properly when view decorations turned on or off.
  radio/src/gui/colorlcd/widget.h
  radio/src/gui/colorlcd/widgets/widgets_container_impl.h
Labels: color, bug/regression ↩️

#5245 fix: Commando8 does not need the startup animation
  radio/src/opentx.cpp
  radio/src/targets/taranis/board.h
Labels: bug 🪲

#5248 fix(color): restore previous 'Fullscreen' functionality and add new 'App mode' layout
  radio/src/gui/colorlcd/layouts/layout1x1AppMode.cpp
  radio/src/gui/colorlcd/layouts/layout_factory_impl.h
  radio/src/gui/colorlcd/view_main.cpp
  radio/src/storage/storage_common.cpp
Labels: color, bug/regression ↩️, user manual change

#5253 chore: remove PCB specific defines in preference to COLORLCD
  radio/src/dataconstants.h
  radio/src/datastructs.h
Labels: compilation, house keeping 🧹

#5233 feat: generic I2C and PCA95xx driver
  radio/src/boards/generic_stm32/CMakeLists.txt
  radio/src/boards/generic_stm32/i2c_bus.cpp
  radio/src/drivers/pca95xx.cpp
  radio/src/drivers/pca95xx.h
  radio/src/hal/i2c_driver.h
  radio/src/targets/common/arm/stm32/lsm6ds_driver.cpp
  radio/src/targets/common/arm/stm32/stm32_i2c_driver.cpp
  radio/src/targets/common/arm/stm32/stm32_i2c_driver.h
  radio/src/targets/horus/cst8xx_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/horus/tp_gt911.cpp
  radio/src/targets/nv14/hal.h
  radio/src/targets/nv14/touch_driver.cpp
  radio/src/targets/pl18/hal.h
  radio/src/targets/pl18/touch_driver.cpp
  radio/src/targets/taranis/eeprom_driver.cpp
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/volume_i2c.cpp
Labels: hardware support

#5255 fix: VersionTag.flavour[] too small for x10express
  radio/src/targets/common/arm/stm32/bootloader/bin_files.h
Labels: bug/regression ↩️

#5254 chore: remove discrepancy in x10/x7 naming
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/firmwares/opentx/opentxinterface.cpp
  fw.json
  tools/build-companion.sh
  tools/build-gh.sh
  tools/commit-tests.sh
  tools/generate-hw-defs.sh
  tools/generate-yaml.sh
  tools/msys2_fetch_and_build_all.sh
Labels: compilation, house keeping 🧹

#5256 fix(bw): fixes and improvements for model setup page
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/212x64/model_setup.cpp
Labels: bug 🪲, enhancement ✨, B&W

#5232 refactor: bootloader & cmake cleanup
  radio/src/CMakeLists.txt
  radio/src/boards/generic_stm32/CMakeLists.txt
  radio/src/boards/generic_stm32/bl_keys.cpp
  radio/src/fonts/CMakeLists.txt
  radio/src/gui/128x64/CMakeLists.txt
  radio/src/gui/212x64/CMakeLists.txt
  radio/src/gui/colorlcd/CMakeLists.txt
  radio/src/hal/CMakeLists.txt
  radio/src/targets/common/arm/stm32/CMakeLists.txt
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/horus/board.cpp
  radio/src/targets/horus/board.h
  radio/src/targets/horus/cst8xx_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/horus/lcd_driver.cpp
  radio/src/targets/horus/lcd_st7796s_driver.cpp
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/nv14/board.cpp
  radio/src/targets/nv14/board.h
  radio/src/targets/nv14/hal.h
  radio/src/targets/nv14/lcd_driver.cpp
  radio/src/targets/pl18/CMakeLists.txt
  radio/src/targets/pl18/board.cpp
  radio/src/targets/pl18/board.h
  radio/src/targets/pl18/hal.h
  radio/src/targets/pl18/key_driver.cpp
  radio/src/targets/pl18/lcd_driver.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
  radio/src/thirdparty/libopenui/src/CMakeLists.txt
  radio/src/thirdparty/libopenui/thirdparty/CMakeLists.txt
Labels: compilation, house keeping 🧹

#5264 fix: nullptr access on empty storage
  radio/src/gui/colorlcd/view_main.cpp
Labels: color, bug/regression ↩️

#5262 fix: configure default internal module for XJT_PXX1
  radio/src/targets/taranis/CMakeLists.txt
Labels: bug 🪲

#5266 fix(horus): pin naming for I2C_B2 pins
  radio/src/targets/horus/hal.h
Labels: bug/regression ↩️

#5268 feat(cpn): add keys to T20 simulator for rotary encoder movement
  companion/src/simulation/simulateduiwidgetJumperT20.cpp
Labels: simulator

#5267 feat: telemetry buffer for all internal modules
  radio/src/targets/common/arm/CMakeLists.txt
  radio/src/telemetry/telemetry.cpp
Labels: bug 🪲, enhancement ✨

#5270 fix: colorlcd compilation with DHELI=NO
  radio/src/gui/colorlcd/model_setup.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
Labels: color, compilation, bug/regression ↩️

#5272 chore: make WS2812 support an option
  radio/src/targets/taranis/CMakeLists.txt
Labels: compilation, house keeping 🧹

#5260 fix: SDIO issues after H7 support
  radio/src/hal/gpio.h
  radio/src/targets/common/arm/stm32/diskio_sdio.cpp
  radio/src/targets/common/arm/stm32/stm32_gpio.cpp
Labels: bug/regression ↩️

#5288 chore: add some Chinese translations
  radio/src/translations/cn.h
Labels: translation

#5286 fix: MPM disable telemetry user choice ignored
  radio/src/pulses/multi.cpp
Labels: bug/regression ↩️

#5271 feat: Jumper T12Max support
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/companion.qrc
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/images/simulator/JumperT12max/bottom.png
  companion/src/images/simulator/JumperT12max/exit.png
  companion/src/images/simulator/JumperT12max/left.png
  companion/src/images/simulator/JumperT12max/menu.png
  companion/src/images/simulator/JumperT12max/page.png
  companion/src/images/simulator/JumperT12max/right-ent.png
  companion/src/images/simulator/JumperT12max/right.png
  companion/src/images/simulator/JumperT12max/top.png
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetJumperT12max.cpp
  companion/src/simulation/simulateduiwidgetJumperT12max.ui
  companion/src/simulation/simulatorwidget.cpp
  fw.json
  radio/src/datastructs.h
  radio/src/hal/rotary_encoder.h
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/bootloader/boot_menu.cpp
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
  radio/src/targets/taranis/usb_descriptor.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-companion.sh
  tools/build-gh.sh
  tools/commit-tests.sh
  tools/generate-hw-defs.sh
  tools/generate-yaml.sh
  tools/msys2_fetch_and_build_all.sh
Labels: hardware support

#5273 feat: Jumper T12Max support
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/companion.qrc
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/images/simulator/JumperT12max/bottom.png
  companion/src/images/simulator/JumperT12max/exit.png
  companion/src/images/simulator/JumperT12max/left.png
  companion/src/images/simulator/JumperT12max/menu.png
  companion/src/images/simulator/JumperT12max/page.png
  companion/src/images/simulator/JumperT12max/right-ent.png
  companion/src/images/simulator/JumperT12max/right.png
  companion/src/images/simulator/JumperT12max/top.png
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetJumperT12max.cpp
  companion/src/simulation/simulateduiwidgetJumperT12max.ui
  companion/src/simulation/simulatorwidget.cpp
  fw.json
  radio/src/hal/rotary_encoder.h
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/bootloader/boot_menu.cpp
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
  radio/src/targets/taranis/usb_descriptor.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-companion.sh
  tools/build-gh.sh
  tools/commit-tests.sh
  tools/generate-hw-defs.sh
  tools/generate-yaml.sh
  tools/msys2_fetch_and_build_all.sh
Labels: hardware support

#5276 chore: ws2812 support to comply with #5232 style
  radio/src/boards/generic_stm32/CMakeLists.txt
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/pl18/CMakeLists.txt
  radio/src/targets/taranis/CMakeLists.txt
Labels: house keeping 🧹

#5293 fix(lua): incorrect name for MIN source
  radio/src/lua/api_general.cpp
Labels: bug 🪲, lua

#5295 chore: delays driver cleanup
  radio/src/targets/common/arm/stm32/board_common.h
  radio/src/targets/common/arm/stm32/delays_driver.cpp
  radio/src/targets/taranis/dwt.h
Labels: house keeping 🧹

#5302 fix: I2C support for H7
  radio/src/boards/generic_stm32/i2c_bus.cpp
  radio/src/hal/i2c_driver.h
  radio/src/targets/common/arm/stm32/stm32_i2c_driver.cpp
Labels: bug 🪲, hardware support

#5301 fix(pl18): key diagnostic screen display trims in wrong mapping
  radio/src/gui/colorlcd/radio_diagkeys.cpp
Labels: bug 🪲

#5308 feat(color): add 1+4 main view screen layout
  companion/src/companion.qrc
  companion/src/images/layouts/mask_layout1+4.png
  radio/src/gui/colorlcd/layouts/layout1+4.cpp
Labels: enhancement ✨, color

#5243 fix: CRSF frame parsing
  radio/src/pulses/crossfire.cpp
  radio/src/tests/crossfire.cpp
Labels: bug 🪲, telemetry 📶, unit tests 🧪

#5321 fix: do not init the watchdog in flash driver
  radio/src/io/bootloader_flash.cpp
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
  radio/src/targets/common/arm/stm32/flash_driver.cpp
Labels: bug/regression ↩️

#5320 feat(bw128): allow long press to open curve edit without entering edit mode
  radio/src/gui/128x64/model_input_edit.cpp
  radio/src/gui/128x64/model_mix_edit.cpp
Labels: UX-UI, B&W

#5313 fix(simu): keyboard trims not working properly
  radio/src/simu.cpp
Labels: bug 🪲, simulator

#4391 fix: inconsistency between SD play value, model custom script screen and value widget
  radio/src/gui/colorlcd/model_mixer_scripts.cpp
  radio/src/gui/colorlcd/widgets/value.cpp
Labels: bug 🪲, UX-UI, lua

#5325 feat: support for Jumper T-Pro S
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/companion.qrc
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/images/simulator/JumperTPROS/bottom.png
  companion/src/images/simulator/JumperTPROS/exit.png
  companion/src/images/simulator/JumperTPROS/left.png
  companion/src/images/simulator/JumperTPROS/menu.png
  companion/src/images/simulator/JumperTPROS/page.png
  companion/src/images/simulator/JumperTPROS/right-ent.png
  companion/src/images/simulator/JumperTPROS/right.png
  companion/src/images/simulator/JumperTPROS/top.png
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetJumperTPROS.cpp
  companion/src/simulation/simulateduiwidgetJumperTPROS.ui
  companion/src/simulation/simulatorwidget.cpp
  fw.json
  radio/src/datastructs.h
  radio/src/simu.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/usb_descriptor.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-companion.sh
  tools/build-gh.sh
  tools/generate-hw-defs.sh
Labels: hardware support

#5290 feat: linker support for firmware in external flash
  radio/src/CMakeLists.txt
  radio/src/boards/generic_stm32/linker/common_sections.ld
  radio/src/boards/generic_stm32/linker/firmware.ld
  radio/src/boards/generic_stm32/linker/stm32f20x/layout.ld
  radio/src/boards/generic_stm32/linker/stm32f40x/layout.ld
  radio/src/boards/generic_stm32/linker/stm32f413/layout.ld
  radio/src/boards/generic_stm32/linker/stm32f429_sdram/layout.ld
  radio/src/io/bootloader_flash.cpp
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
  radio/src/targets/common/arm/stm32/f2/CMakeLists.txt
  radio/src/targets/common/arm/stm32/flash_driver.cpp
  radio/src/targets/common/arm/stm32/flash_driver.h
  radio/src/targets/horus/board.h
  radio/src/targets/nv14/board.h
  radio/src/targets/pl18/board.h
  radio/src/targets/taranis/board.h
Labels: hardware support

#5235 feat(color): allow changing the size of topbar widgets
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  companion/src/firmwares/modeldata.h
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/layouts/topbar_impl.cpp
  radio/src/gui/colorlcd/screen_user_interface.cpp
  radio/src/gui/colorlcd/screen_user_interface.h
  radio/src/storage/storage_common.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t15.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/thirdparty/libopenui/src/choice.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, color

#5331 fix: lua axis name for T15, T14, T12Max
  radio/util/hw_defs/legacy_names.py
Labels: bug 🪲

#5269 chore(bw): simplify navigation code
  radio/src/gui/128x64/model_curve_edit.cpp
  radio/src/gui/128x64/model_gvars.cpp
  radio/src/gui/128x64/model_input_edit.cpp
  radio/src/gui/128x64/model_logical_switches.cpp
  radio/src/gui/128x64/model_mix_edit.cpp
  radio/src/gui/128x64/model_outputs.cpp
  radio/src/gui/128x64/model_select.cpp
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/128x64/view_statistics.cpp
  radio/src/gui/128x64/widgets.cpp
  radio/src/gui/212x64/gui.h
  radio/src/gui/212x64/model_failsafe.cpp
  radio/src/gui/212x64/model_gvars.cpp
  radio/src/gui/212x64/model_logical_switches.cpp
  radio/src/gui/212x64/model_outputs.cpp
  radio/src/gui/212x64/model_select.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/212x64/view_statistics.cpp
  radio/src/gui/212x64/widgets.cpp
  radio/src/gui/common/stdlcd/draw_functions.cpp
  radio/src/gui/common/stdlcd/menus.cpp
  radio/src/gui/common/stdlcd/model_inputs.cpp
  radio/src/gui/common/stdlcd/model_mixes.cpp
  radio/src/gui/common/stdlcd/model_module_options.cpp
  radio/src/gui/common/stdlcd/model_receiver_options.cpp
  radio/src/gui/common/stdlcd/model_setup_pxx2.cpp
  radio/src/gui/common/stdlcd/model_usbjoystick.cpp
  radio/src/gui/common/stdlcd/popups.cpp
  radio/src/gui/common/stdlcd/radio_trainer.cpp
  radio/src/gui/common/stdlcd/view_telemetry.cpp
  radio/src/gui/navigation/navigation.cpp
  radio/src/gui/navigation/navigation_9x.cpp
  radio/src/gui/navigation/navigation_x7.cpp
  radio/src/gui/navigation/navigation_x9d.cpp
  radio/src/gui/navigation/navigation_xlite.cpp
  radio/src/keys.cpp
Labels: UX-UI, B&W, house keeping 🧹

#5326 feat: support for Jumper T-Pro S
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/companion.qrc
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/images/simulator/JumperTPROS/bottom.png
  companion/src/images/simulator/JumperTPROS/exit.png
  companion/src/images/simulator/JumperTPROS/left.png
  companion/src/images/simulator/JumperTPROS/menu.png
  companion/src/images/simulator/JumperTPROS/page.png
  companion/src/images/simulator/JumperTPROS/right-ent.png
  companion/src/images/simulator/JumperTPROS/right.png
  companion/src/images/simulator/JumperTPROS/top.png
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetJumperTPROS.cpp
  companion/src/simulation/simulateduiwidgetJumperTPROS.ui
  companion/src/simulation/simulatorwidget.cpp
  fw.json
  radio/src/datastructs.h
  radio/src/simu.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/usb_descriptor.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-companion.sh
  tools/build-gh.sh
  tools/generate-hw-defs.sh
Labels: hardware support

#5278 feat: add "Trims" option to Reset special function
  companion/src/firmwares/customfunctiondata.cpp
  companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
  companion/src/firmwares/opentx/opentxeeprom.cpp
  radio/src/dataconstants.h
  radio/src/functions.cpp
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨

#5333 fix(color): curve edit lag when changing point count, t15 graph size
  radio/src/gui/colorlcd/curveedit.cpp
Labels: color, UX-UI

#5329 fix(color): T15 curve preview, cleanup curve edit layout
  radio/src/gui/colorlcd/curveedit.cpp
  radio/src/gui/colorlcd/curveedit.h
Labels: color, bug/regression ↩️

#5335 chore: add legacy_names to gtest
  radio/src/tests/lua.cpp
Labels: lua, unit tests 🧪

#5341 fix(color): model select layout on T15 not full height
  radio/src/gui/colorlcd/model_select.h
Labels: bug 🪲, color, UX-UI

#5338 fix(color): restore CHANGED event handler for Choice class
  radio/src/thirdparty/libopenui/src/choice.cpp
  radio/src/thirdparty/libopenui/src/choice.h
Labels: color, bug/regression ↩️

#5343 fix(radio): ensure customisable switch set as Toggle starts in the OFF state.
  radio/src/gui/colorlcd/function_switches.cpp
  radio/src/switches.cpp
Labels: bug 🪲, color, B&W

#5314 feat: add precision setting for mix delay up & down
  companion/src/firmwares/edgetx/yaml_mixdata.cpp
  companion/src/firmwares/mixdata.h
  companion/src/modeledit/mixerdialog.cpp
  companion/src/modeledit/mixerdialog.ui
  companion/src/modelprinter.cpp
  radio/src/datastructs_private.h
  radio/src/gui/128x64/model_mix_edit.cpp
  radio/src/gui/212x64/model_mix_edit.cpp
  radio/src/gui/colorlcd/mixer_edit_adv.cpp
  radio/src/gui/colorlcd/mixer_edit_adv.h
  radio/src/mixer.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t15.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, rn: feature

#5342 feat(bw): do not show time on main view when RTC not set
  radio/src/gui/128x64/view_main.cpp
  radio/src/gui/212x64/view_main.cpp
  radio/src/rtc.cpp
  radio/src/rtc.h
Labels: UX-UI, B&W

#5319 fix(el18): uart auto oversampling calculation
  radio/src/hal/module_port.cpp
  radio/src/hal/serial_driver.h
  radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
Labels: bug 🪲, house keeping 🧹

#5355 feat(dsm): process new format for Spektrum Sky_ID GPS frames
  radio/src/telemetry/spektrum.cpp
Labels: enhancement ✨, not-our-bug
