Repository EdgeTX/edgetx, pull requests merged in 2024-06, with the labels that each got.

#5094 fix(x9d): incorrect switch positions on main view
  radio/util/hw_defs/switch_config.py
Labels: B&W, bug/regression ↩️

#4994 fix: enforce custom switches rules when configuring
  companion/src/firmwares/modeldata.cpp
  companion/src/firmwares/modeldata.h
  companion/src/modeledit/setup.cpp
  companion/src/modeledit/setup.h
  companion/src/modeledit/setup_function_switches.ui
  companion/src/multimodelprinter.cpp
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/128x64/radio_diagkeys.cpp
  radio/src/myeeprom.h
  radio/src/opentx_constants.h
  radio/src/switches.cpp
  radio/src/switches.h
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
  radio/src/translations/untranslated.h
Labels: bug 🪲

#5098 chore: allow X7 hardware debugging
  radio/src/targets/taranis/hal.h
Labels: compilation

#5096 fix(bw128): improve logical switch navigation & editing
  radio/src/gui/128x64/model_logical_switches.cpp
Labels: bug 🪲

#5101 fix(bw128): long press for outputs page popup menu
  radio/src/gui/128x64/model_outputs.cpp
Labels: UX-UI, B&W

#4907 feat: ELRS bind command support
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/colorlcd/module_setup.cpp
  radio/src/gui/colorlcd/radio_version.cpp
  radio/src/gui/common/stdlcd/radio_version.cpp
  radio/src/gui/gui_common.cpp
  radio/src/pulses/crossfire.cpp
  radio/src/pulses/modules_helpers.h
  radio/src/telemetry/crossfire.cpp
  radio/src/telemetry/crossfire.h
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, rn: feature

#5103 fix: compilation without audio or modules
  radio/src/audio.h
  radio/src/telemetry/crossfire.h
Labels: bug 🪲, compilation

#5068 perf(color): reduce bootloader size
  radio/src/gui/colorlcd/lcd.cpp
  radio/src/targets/horus/lcd_driver.cpp
  radio/src/targets/simu/simulcd.cpp
  radio/src/thirdparty/libopenui/thirdparty/CMakeLists.txt
Labels: color, house keeping 🧹

#4978 feat: allow Sticky LS state to persist across EM or optionally across reboot
  companion/src/firmwares/edgetx/yaml_logicalswitchdata.cpp
  companion/src/firmwares/logicalswitchdata.h
  companion/src/modeledit/logicalswitches.cpp
  companion/src/modeledit/logicalswitches.h
  companion/src/modelprinter.cpp
  radio/src/datastructs_private.h
  radio/src/gui/128x64/model_logical_switches.cpp
  radio/src/gui/212x64/model_logical_switches.cpp
  radio/src/gui/212x64/widgets.cpp
  radio/src/gui/colorlcd/model_logical_switches.cpp
  radio/src/opentx.cpp
  radio/src/storage/storage_common.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/switches.cpp
  radio/src/switches.h
  radio/src/translations.h
  radio/src/translations/fr.h
Labels: enhancement ✨

#4987 feat(color): support PPM_US setting
  radio/src/gui/colorlcd/channel_bar.cpp
  radio/src/gui/colorlcd/channel_bar.h
  radio/src/gui/colorlcd/custom_failsafe.cpp
  radio/src/gui/colorlcd/gvar_numberedit.cpp
  radio/src/gui/colorlcd/gvar_numberedit.h
  radio/src/gui/colorlcd/model_outputs.cpp
  radio/src/gui/colorlcd/output_edit.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/gui/colorlcd/widgets/outputs.cpp
  radio/src/strhelpers.cpp
  radio/src/strhelpers.h
Labels: color, UX-UI

#5105 fix(color): slow prec not updating fields when changing precision
  radio/src/gui/colorlcd/mixer_edit_adv.cpp
Labels: bug 🪲, color

#5102 chores: update LZ4 to latest
  radio/src/thirdparty/libopenui/thirdparty/lz4/lz4.c
Labels: house keeping 🧹

#5109 fix(bw128): telemetry source name overlaps V1 value on logical switch list view
  radio/src/gui/128x64/lcd.cpp
Labels: bug 🪲, UX-UI, B&W

#5117 fix(simulator): mapping of labels to controls
  companion/src/simulation/simulatorwidget.cpp
Labels: simulator, bug/regression ↩️

#5119 fix(mlink): sometimes need > 1s timeout for MLink telem
  radio/src/telemetry/mlink.cpp
Labels: telemetry 📶

#5123 fix(cpn): model print flight mode trim labels
  companion/src/multimodelprinter.cpp
Labels: companion, bug/regression ↩️

#5116 fix(bw128): column spacing for LS allowing for max values
  radio/src/gui/128x64/model_logical_switches.cpp
Labels: UX-UI, B&W

#5124 fix: timings for MPM update due to faster F4 MCUs
  radio/src/io/multi_firmware_update.cpp
Labels: bug 🪲

#5108 fix(lua): getFieldInfo() not returning switch info
  radio/src/lua/api_general.cpp
  radio/util/hw_defs/lua_inputs.jinja
Labels: lua, bug/regression ↩️

#5115 feat: Jumper T15 IPS screen support
  radio/src/gui/colorlcd/radio_version.cpp
  radio/src/targets/horus/board.h
  radio/src/targets/horus/hal.h
  radio/src/targets/horus/lcd_st7796s_driver.cpp
Labels: hardware support

#4933 feat(bw128): add option to invert LCD/OLED display
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
  radio/src/datastructs_private.h
  radio/src/gui/common/stdlcd/radio_hardware.cpp
  radio/src/storage/sdcard_yaml.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/targets/simu/simpgmspace.cpp
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
Labels: enhancement ✨, B&W

#5046 feat(radio): increase length of sound/script file name to 8 for SF/GF
  companion/src/firmwares/opentx/opentxinterface.cpp
  radio/src/dataconstants.h
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
Labels: enhancement ✨

#5062 fix(cpn): change the default battery range to match firmware
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/generalsettings.cpp
Labels: bug 🪲, companion, simulator

#5135 fix(cpn): windows build failing because sbrk does not exist on mingw
  radio/src/lv_conf.h
Labels: companion, compilation

#5107 fix(color): issues with long press key handling.
  radio/src/gui/colorlcd/LvglWrapper.cpp
  radio/src/gui/colorlcd/curve_param.cpp
  radio/src/gui/colorlcd/curve_param.h
  radio/src/gui/colorlcd/curveedit.cpp
  radio/src/gui/colorlcd/curveedit.h
  radio/src/gui/colorlcd/fullscreen_dialog.cpp
  radio/src/gui/colorlcd/fullscreen_dialog.h
  radio/src/gui/colorlcd/input_edit.cpp
  radio/src/gui/colorlcd/listbox.cpp
  radio/src/gui/colorlcd/listbox.h
  radio/src/gui/colorlcd/model_curves.cpp
  radio/src/gui/colorlcd/model_curves.h
  radio/src/gui/colorlcd/sourcechoice.cpp
  radio/src/gui/colorlcd/sourcechoice.h
  radio/src/gui/colorlcd/switchchoice.cpp
  radio/src/gui/colorlcd/switchchoice.h
  radio/src/gui/colorlcd/view_main.cpp
  radio/src/gui/colorlcd/view_main.h
  radio/src/gui/colorlcd/widget.cpp
  radio/src/gui/colorlcd/widget.h
  radio/src/keys.cpp
  radio/src/keys.h
  radio/src/thirdparty/libopenui/src/button.cpp
  radio/src/thirdparty/libopenui/src/button.h
  radio/src/thirdparty/libopenui/src/choice.cpp
  radio/src/thirdparty/libopenui/src/choice.h
  radio/src/thirdparty/libopenui/src/menu.cpp
  radio/src/thirdparty/libopenui/src/menu.h
  radio/src/thirdparty/libopenui/src/menutoolbar.cpp
  radio/src/thirdparty/libopenui/src/menutoolbar.h
  radio/src/thirdparty/libopenui/src/numberedit.cpp
  radio/src/thirdparty/libopenui/src/window.cpp
  radio/src/thirdparty/libopenui/src/window.h
Labels: color, UX-UI, bug/regression ↩️

#5122 chore: remove unused FUNC_FIRST_WITHOUT_ENABLE, DEFAULT_THEME
  radio/src/dataconstants.h
  radio/src/targets/horus/CMakeLists.txt
Labels: house keeping 🧹

#5016 feat: customisable switches generated sources
  companion/src/constants.h
  companion/src/datamodels/compounditemmodels.cpp
  companion/src/firmwares/edgetx/yaml_rawsource.cpp
  companion/src/firmwares/rawsource.cpp
  companion/src/firmwares/rawsource.h
  companion/src/modeledit/setup.cpp
  radio/src/dataconstants.h
  radio/src/gui/gui_common.cpp
  radio/src/mixer.cpp
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/strhelpers.cpp
  radio/src/strhelpers.h
  radio/src/switches.cpp
  radio/src/switches.h
  radio/src/targets/horus/board.h
  radio/src/targets/taranis/board.h
Labels: enhancement ✨, user manual change

#5136 fix(color): remove unnecessary updates of channel bar
  radio/src/gui/colorlcd/channel_bar.cpp
  radio/src/gui/colorlcd/channel_bar.h
Labels: color, UX-UI

#5017 feat: option to disable power on/off haptic
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
  radio/src/datastructs_private.h
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/opentx.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t15.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, user manual change, needs:translation

#5141 fix(cpn): crash when going into radio settings due to customisable switch groups source
  companion/src/datamodels/compounditemmodels.cpp
  companion/src/firmwares/rawsource.cpp
  radio/src/gui/colorlcd/sourcechoice.cpp
Labels: bug/regression ↩️

#5134 feat: add 0.5 second option to power on/off delays
  companion/src/generaledit/generalsetup.cpp
  companion/src/generaledit/generalsetup.h
  companion/src/generaledit/generalsetup.ui
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/212x64/radio_setup.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/gui/colorlcd/startup_shutdown.cpp
  radio/src/opentx.cpp
  radio/src/opentx.h
  radio/src/translations/untranslated.h
Labels: enhancement ✨

#5120 chore(translation): update SE for firmware and companion
  companion/src/translations/companion_sv.ts
  radio/src/translations/se.h
Labels: translation

#5147 fix(cpn): simulator radio output channel labels
  companion/src/simulation/radiooutputswidget.cpp
Labels: simulator, bug/regression ↩️

#5145 chore(cpn): cleanup build warnings
  companion/src/generaledit/calibration.cpp
  companion/src/mdichild.cpp
  companion/src/updates/repobuild.h
  companion/src/updates/repogithub.h
  companion/src/updates/updatecloudbuild.cpp
Labels: companion, compilation, house keeping 🧹

#5152 fix(cpn): simulator may get stuck on splash screen.
  radio/src/opentx.cpp
Labels: bug 🪲, simulator

#5149 fix: check both SBUS trainer ports regardless of TRAINER_MODULE_SBUS_USART
  radio/src/gui/gui_common.cpp
  radio/src/trainer.cpp
Labels: bug/regression ↩️

#5159 fix(radio): close file handle if sound file cannot be played
  radio/src/audio.cpp
Labels: house keeping 🧹

#5155 fix(cpn): more fixes to RawSource calls
  companion/src/modeledit/setup.cpp
  companion/src/modelprinter.cpp
  companion/src/simulation/joystickdialog.cpp
Labels: companion, bug/regression ↩️

#5156 chore(bw): remove unused READ_ONLY and READ_ONLY_UNLOCKED macros
  radio/src/gui/128x64/model_custom_scripts.cpp
  radio/src/gui/128x64/model_display.cpp
  radio/src/gui/128x64/model_failsafe.cpp
  radio/src/gui/128x64/model_outputs.cpp
  radio/src/gui/128x64/model_select.cpp
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/gui/128x64/radio_calibration.cpp
  radio/src/gui/212x64/model_custom_scripts.cpp
  radio/src/gui/212x64/model_display.cpp
  radio/src/gui/212x64/model_logical_switches.cpp
  radio/src/gui/212x64/model_outputs.cpp
  radio/src/gui/212x64/model_select.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/212x64/radio_calibration.cpp
  radio/src/gui/colorlcd/radio_sdmanager.cpp
  radio/src/gui/common/stdlcd/calibration.cpp
  radio/src/gui/common/stdlcd/model_curves.cpp
  radio/src/gui/common/stdlcd/model_inputs.cpp
  radio/src/gui/common/stdlcd/model_mixes.cpp
  radio/src/gui/common/stdlcd/radio_sdmanager.cpp
  radio/src/gui/navigation/navigation_9x.cpp
  radio/src/gui/navigation/navigation_x7.cpp
  radio/src/gui/navigation/navigation_x9d.cpp
  radio/src/gui/navigation/navigation_xlite.cpp
  radio/src/opentx.h
Labels: house keeping 🧹

#5154 fix(bw212): main view sliders, omitted sensor count display
  radio/src/gui/212x64/model_telemetry.cpp
  radio/src/gui/212x64/view_main.cpp
Labels: B&W

#5151 fix(cpn): profile conversion of models and settings
  companion/src/firmwares/generalsettings.cpp
  companion/src/firmwares/moduledata.cpp
  companion/src/firmwares/radiodataconversionstate.cpp
  companion/src/firmwares/radiodataconversionstate.h
  companion/src/firmwares/rawsource.cpp
  companion/src/firmwares/rawswitch.cpp
Labels: bug 🪲, companion

#5164 fix(color): cosmetic focus issue on text and number edit fields
  radio/src/thirdparty/libopenui/src/numberedit.cpp
  radio/src/thirdparty/libopenui/src/textedit.cpp
Labels: color, UX-UI, bug/regression ↩️

#5166 chore(color): remove unused heading from UI
  radio/src/gui/colorlcd/function_switches.cpp
Labels: color, UX-UI

#5169 fix(cpn): binary import of multi position switches
  companion/src/firmwares/opentx/opentxeeprom.cpp
Labels: companion, bug/regression ↩️

#5146 feat(color): delay image load on manage models page
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/thirdparty/libopenui/src/bitmapbuffer_fileio.cpp
  radio/src/thirdparty/libopenui/src/static.cpp
  radio/src/thirdparty/libopenui/src/static.h
Labels: color, UX-UI

#5160 fix: hide 'invert' toggle for multipos switches
  companion/src/firmwares/generalsettings.cpp
  companion/src/generaledit/hardware.cpp
  companion/src/generaledit/hardware.h
  radio/src/gui/colorlcd/hw_inputs.cpp
  radio/src/gui/colorlcd/hw_inputs.h
  radio/src/gui/common/stdlcd/radio_hardware.cpp
Labels: bug 🪲

#5170 fix(simulator): incorrect initialisation of preflight checks
  radio/src/model_init.cpp
Labels: bug 🪲, simulator

#5168 feat(color): hide customizable switch screen startup header when not used
  radio/src/gui/colorlcd/function_switches.cpp
  radio/src/gui/colorlcd/function_switches.h
Labels: color, UX-UI

#4887 feat(lua): support for using LVGL objects on colorlcd
  radio/src/gui/colorlcd/CMakeLists.txt
  radio/src/gui/colorlcd/layouts/layout_factory_impl.cpp
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/gui/colorlcd/radio_sdmanager.cpp
  radio/src/gui/colorlcd/radio_tools.cpp
  radio/src/gui/colorlcd/standalone_lua.cpp
  radio/src/gui/colorlcd/standalone_lua.h
  radio/src/gui/colorlcd/view_main.h
  radio/src/gui/colorlcd/widget.cpp
  radio/src/gui/colorlcd/widget.h
  radio/src/gui/colorlcd/widgets/timer.cpp
  radio/src/lua/CMakeLists.txt
  radio/src/lua/api_colorlcd.cpp
  radio/src/lua/api_colorlcd.h
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/api_general.cpp
  radio/src/lua/interface.cpp
  radio/src/lua/lua_api.h
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
  radio/src/lua/lua_widget.cpp
  radio/src/lua/lua_widget.h
  radio/src/lua/lua_widget_factory.h
  radio/src/lua/widgets.cpp
  radio/src/lv_conf.h
  radio/src/main.cpp
  radio/src/thirdparty/Lua/src/linit.c
  radio/src/thirdparty/libopenui/src/static.cpp
  radio/src/thirdparty/libopenui/src/static.h
  radio/src/thirdparty/libopenui/src/window.h
Labels: enhancement ✨, color, lua

#5175 fix: revise T15 PCBREV
  radio/src/targets/horus/hal.h
Labels: house keeping 🧹

#5174 fix: revise T15 PCBREV
  radio/src/gui/colorlcd/radio_version.cpp
  radio/src/targets/horus/hal.h
Labels: hardware support, house keeping 🧹

#5178 fix(bootloader): use ASCII only strings for NV14/EL18
  radio/src/targets/nv14/bootloader/boot_menu.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: bug 🪲

#5184 fix(color): slow scrolling on model select page
  radio/src/gui/colorlcd/file_preview.cpp
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/thirdparty/libopenui/src/bitmapbuffer.cpp
  radio/src/thirdparty/libopenui/src/bitmapbuffer.h
  radio/src/thirdparty/libopenui/src/bitmapbuffer_fileio.cpp
  radio/src/thirdparty/libopenui/src/static.cpp
  radio/src/thirdparty/libopenui/src/static.h
Labels: color, bug/regression ↩️

#5185 fix(color): memory leak in setup pages
  radio/src/gui/colorlcd/tabsgroup.cpp
  radio/src/gui/colorlcd/tabsgroup.h
  radio/src/thirdparty/libopenui/src/static.cpp
Labels: color, house keeping 🧹

#5183 fix(cpn): logical switch move units refresh
  companion/src/modeledit/logicalswitches.cpp
Labels: bug 🪲, companion

#5187 feat(cpn): add filenames to model compare
  companion/src/comparedialog.cpp
  companion/src/comparedialog.h
  companion/src/mdichild.cpp
  companion/src/modelslist.cpp
  companion/src/modelslist.h
Labels: enhancement ✨, companion

#5190 fix: serial power port handling
  radio/src/serial.cpp
  radio/src/targets/common/arm/stm32/pwr_driver.cpp
Labels: bug/regression ↩️

#5193 fix: customisable switch custom name not displayed
  radio/src/switches.cpp
Labels: bug/regression ↩️

#5195 fix: allow selection of axis as a source
  radio/src/opentx.h
Labels: bug 🪲

#5197 chore: 2.10 version of #5190 GPIO code
  radio/src/targets/common/arm/stm32/pwr_driver.cpp
Labels: house keeping 🧹

#5200 fix(color): radio stuck when trying to close nested standalone script
  radio/src/gui/colorlcd/standalone_lua.cpp
Labels: bug/regression ↩️

#5201 fix(color): issues with file chooser
  radio/src/gui/colorlcd/model_setup.cpp
  radio/src/thirdparty/libopenui/src/choice.cpp
  radio/src/thirdparty/libopenui/src/choice.h
  radio/src/thirdparty/libopenui/src/filechoice.cpp
  radio/src/thirdparty/libopenui/src/menutoolbar.cpp
Labels: color, UX-UI, bug/regression ↩️

#5205 fix(color): incorrect size of number edit in widget settings for portrait layout.
  radio/src/gui/colorlcd/widget_settings.cpp
Labels: bug 🪲, color

#5148 fix: reduce file system corruption from standalone Lua scripts
  radio/src/targets/common/arm/stm32/diskio_sdio.cpp
  radio/src/thirdparty/FatFs/ffconf.h
Labels: bug 🪲

#5198 DA update radio and companion
  companion/src/translations/companion_da.ts
  radio/src/translations/da.h
Labels: translation

#5204 fix(color): issues with color picker dialog
  radio/src/gui/colorlcd/color_editor.cpp
  radio/src/gui/colorlcd/color_picker.cpp
  radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
  radio/src/gui/colorlcd/themes/etx_lv_theme.h
Labels: color, UX-UI, bug/regression ↩️

#5194 fix(radio): various issues with rotary encoder.
  radio/src/gui/colorlcd/LvglWrapper.cpp
  radio/src/hal/rotary_encoder.h
  radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/simu/simpgmspace.cpp
  radio/src/targets/taranis/hal.h
Labels: bug 🪲

#5206 fix(color): first button press on widget settings page may not register
  radio/src/gui/colorlcd/widget.cpp
Labels: color, bug/regression ↩️

#5208 fix(color): issues with menus (possible EM, double loading of content)
  radio/src/gui/colorlcd/screen_setup.cpp
  radio/src/gui/colorlcd/sourcechoice.cpp
  radio/src/gui/colorlcd/switchchoice.cpp
  radio/src/thirdparty/libopenui/src/filechoice.cpp
  radio/src/thirdparty/libopenui/src/menu.cpp
Labels: color, UX-UI, em, house keeping 🧹

#5211 fix(color): choice button being skipped when using rotary encoder
  radio/src/thirdparty/libopenui/src/choice.cpp
Labels: color, bug/regression ↩️

#5212 fix(color): standalone Lua syntax errors or missing run() may cause EM
  radio/src/lua/interface.cpp
Labels: color, em, bug/regression ↩️

#5209 fix: RTC warning not being shown
  radio/src/gui/colorlcd/radio_hardware.cpp
  radio/src/gui/colorlcd/radio_hardware.h
  radio/src/opentx.cpp
  radio/src/opentx.h
Labels: bug/regression ↩️

#5219 fix(color): crash when changing 'Mode' for 'Adjust' SF
  radio/src/gui/colorlcd/special_functions.cpp
  radio/src/thirdparty/libopenui/src/choice.cpp
Labels: color, bug/regression ↩️

#5221 chore: remove useless editGVarFieldValue
  radio/src/gui/128x64/widgets.cpp
Labels: house keeping 🧹

#5224 Save telemetry sensor generated by LUA setTelemetryValue()
  radio/src/lua/api_general.cpp
Labels: lua, bug/regression ↩️

#5226 fix(color): block radio startup until checklist is closed.
  radio/src/gui/colorlcd/view_text.cpp
  radio/src/gui/colorlcd/view_text.h
  radio/src/opentx.cpp
Labels: bug 🪲, color

#5227 fix(color): block radio startup until checklist is closed.
  radio/src/gui/colorlcd/view_text.cpp
  radio/src/gui/colorlcd/view_text.h
  radio/src/opentx.cpp
Labels: bug 🪲, color

#5199 chore: bump macos runner version
  .github/workflows/macosx_cpn.yml
Labels: companion

#5225 chore(build): simplify the CHKSIZE macros
  radio/src/datastructs.h
Labels: compilation, house keeping 🧹

#5179 feat(color): additions to Lvgl for Lua scripts
  companion/src/firmwares/edgetx/yaml_screendata.cpp
  radio/src/gui/colorlcd/LvglWrapper.cpp
  radio/src/gui/colorlcd/color_editor.cpp
  radio/src/gui/colorlcd/color_list.cpp
  radio/src/gui/colorlcd/color_picker.cpp
  radio/src/gui/colorlcd/color_picker.h
  radio/src/gui/colorlcd/colors.cpp
  radio/src/gui/colorlcd/colors.h
  radio/src/gui/colorlcd/curve.cpp
  radio/src/gui/colorlcd/custom_failsafe.cpp
  radio/src/gui/colorlcd/layouts/layout2x4.cpp
  radio/src/gui/colorlcd/page.cpp
  radio/src/gui/colorlcd/page.h
  radio/src/gui/colorlcd/popups.cpp
  radio/src/gui/colorlcd/select_fab_carousel.cpp
  radio/src/gui/colorlcd/special_functions.cpp
  radio/src/gui/colorlcd/standalone_lua.cpp
  radio/src/gui/colorlcd/standalone_lua.h
  radio/src/gui/colorlcd/theme_manager.cpp
  radio/src/gui/colorlcd/theme_manager.h
  radio/src/gui/colorlcd/themes/etx_lv_theme.cpp
  radio/src/gui/colorlcd/themes/etx_lv_theme.h
  radio/src/gui/colorlcd/view_about.cpp
  radio/src/gui/colorlcd/view_about.h
  radio/src/gui/colorlcd/widget.cpp
  radio/src/gui/colorlcd/widget_settings.cpp
  radio/src/gui/colorlcd/widgets/gauge.cpp
  radio/src/gui/colorlcd/widgets/modelbmp.cpp
  radio/src/gui/colorlcd/widgets/outputs.cpp
  radio/src/gui/colorlcd/widgets/radio_info.cpp
  radio/src/gui/colorlcd/widgets/text.cpp
  radio/src/gui/colorlcd/widgets/timer.cpp
  radio/src/gui/colorlcd/widgets/value.cpp
  radio/src/gui/colorlcd/widgets_setup.cpp
  radio/src/lua/api_colorlcd.cpp
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/interface.cpp
  radio/src/lua/lua_api.h
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
  radio/src/lua/lua_widget.cpp
  radio/src/lua/lua_widget_factory.cpp
  radio/src/lua/widgets.cpp
  radio/src/main.cpp
  radio/src/storage/storage_common.cpp
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/thirdparty/libopenui/src/bitmapbuffer.h
  radio/src/thirdparty/libopenui/src/bitmapbuffer_draw_extra.cpp
  radio/src/thirdparty/libopenui/src/button_matrix.cpp
  radio/src/thirdparty/libopenui/src/libopenui_defines.h
  radio/src/thirdparty/libopenui/src/slider.cpp
  radio/src/thirdparty/libopenui/src/static.cpp
  radio/src/thirdparty/libopenui/src/static.h
  radio/src/thirdparty/libopenui/src/table.cpp
Labels: enhancement ✨, color
