Repository EdgeTX/edgetx, pull requests merged in 2024-01, with the labels that each got.

#4475 chores(pl18/nv14): Clean up cmake and boot menu
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/nv14/bootloader/boot_menu.cpp
  radio/src/targets/pl18/CMakeLists.txt
  radio/src/targets/pl18/board.cpp
  radio/src/targets/pl18/bootloader/boot_menu.cpp
  radio/src/targets/pl18/hal.h
Labels: compilation

#4500 fix(sdio): Check card state after each block written
  radio/src/targets/common/arm/stm32/diskio_sdio.cpp
Labels: bug/regression ↩️

#4502 fix: timers throttle condition on surface radio
  radio/src/tests/timers.cpp
  radio/src/timers.cpp
Labels: bug 🪲

#4490 fix(bw): Channel Monitor view not working correctly on startup
  radio/src/gui/128x64/view_channels.cpp
  radio/src/gui/212x64/view_channels.cpp
  radio/src/opentx.h
Labels: bug 🪲, B&W

#4489 fix(x9d+): Default pots and sliders config
  radio/util/hw_defs/pot_config.py
Labels: bug/regression ↩️

#4472 fix: Invert MT12 T5 direction
  radio/src/targets/taranis/hal.h
Labels: bug 🪲

#4501 fix(lua): re-implement luaSetSerialBaudrate
  radio/src/gui/colorlcd/view_statistics.cpp
  radio/src/gui/colorlcd/widgets/radio_info.cpp
  radio/src/gui/gui_common.cpp
  radio/src/gui/gui_common.h
  radio/src/lua/api_general.cpp
  radio/src/serial.cpp
  radio/src/serial.h
Labels: lua-api, bug/regression ↩️

#4474 chore(cpn): Update Danish translations
  companion/src/translations/companion_da.ts
Labels: companion, translation

#4464 fix(firmware): False triggering of user activity.
  radio/src/inactivity_timer.cpp
Labels: bug/regression ↩️

#4480 chore: improve 128x64 calibration strings
  radio/src/translations/en.h
Labels: translation

#4498 fix(color): Special/Global functions from 2.9 not imported correctly in 2.10.
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Labels: rn: warning, bug/regression ↩️, storage

#4503 feat(pl18): Charging LED animation
  radio/src/targets/pl18/battery_driver.cpp
  radio/src/targets/pl18/board.cpp
Labels: enhancement ✨

#4505 Update ru.h
  radio/src/translations/ru.h
Labels: translation

#4465 feat: Use trim as a 3 pos toggle switch source
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  companion/src/helpers.h
  companion/src/modeledit/flightmodes.cpp
  companion/src/modelprinter.cpp
  radio/src/gui/128x64/model_flightmodes.cpp
  radio/src/gui/212x64/model_flightmodes.cpp
  radio/src/gui/colorlcd/draw_functions.cpp
  radio/src/gui/colorlcd/model_flightmodes.cpp
  radio/src/gui/common/stdlcd/draw_functions.cpp
  radio/src/mixer.cpp
  radio/src/myeeprom.h
  radio/src/opentx.cpp
Labels: enhancement ✨

#4510 chore(translation): Correct notice of Simulator import settings for DA
  companion/src/translations/companion_da.ts
Labels: companion, translation

#4083 fix: Properly scale PREC2 sensor values using "ratio"
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/telemetry/telemetry_sensors.cpp
Labels: telemetry 📶

#4512 chore(cpn): python-lz4 for win32 no longer in mingw repo
  .github/workflows/win-cpn-32.yml
Labels: companion, compilation

#4515 Telemetry(DSM) Fix for Longitude greater than 99 deg
  radio/src/telemetry/spektrum.cpp
Labels: telemetry 📶

#4523 feat: set better internal crossfire module default baudrate
  radio/src/opentx.cpp
Labels: enhancement ✨

#4517 fix(firmware): Behaviour of trim set to 3POS when used in SF Adjust GV function.
  radio/src/opentx.cpp
Labels: bug 🪲

#4531 fix(color): 'Unlabeled' option does not appear in labels list.
  radio/src/storage/modelslist.cpp
Labels: color, bug/regression ↩️

#4525 radio.yml / model.yml tag hatsMode for featured radios only
  radio/src/datastructs_private.h
  radio/src/model_init.cpp
  radio/src/opentx.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
Labels: house keeping 🧹

#4529 Horus X10 Touch Screen Mod Update-EXPRESS PCBREV check failing in cold temps
  radio/src/targets/common/arm/stm32/pwr_driver.cpp
  radio/src/targets/horus/hal.h
Labels: don't merge, bug/regression ↩️

#4533 2.9 : Linux CPN AppImage SSL packaging
  .github/workflows/linux_cpn.yml
  .github/workflows/macosx_cpn.yml
  .github/workflows/nightly.yml
  .github/workflows/win_cpn-32.yml
  .github/workflows/win_cpn-64.yml
  cmake/FindDfuutil.cmake
  cmake/FindLibusb1.cmake
  cmake/NativeTargets.cmake
  companion/src/CMakeLists.txt
  companion/src/CPackLinuxDeploy.cmake.in
  companion/src/CPackLinuxDeployQt.cmake.in
Labels: companion, compilation, bug/regression ↩️

#4542 fix: USB device name, remove the hack
  radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp
Labels: bug/regression ↩️

#4545 chore: usb names
  radio/src/targets/horus/usb_descriptor.h
  radio/src/targets/taranis/usb_descriptor.h
Labels: house keeping 🧹

#4550 fix: strengthen lcd buffer protection
  radio/src/gui/128x64/lcd.cpp
  radio/src/gui/128x64/lcd.h
  radio/src/gui/common/stdlcd/model_curves.cpp
Labels: bug 🪲, B&W

#4543 feat(fw): Jumper T14 support
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  fw.json
  radio/src/datastructs.h
  radio/src/hal/rotary_encoder.h
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/lcd_driver_spi.cpp
  radio/src/targets/taranis/usb_descriptor.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/boards.py
  tools/build-companion.sh
  tools/build-gh.sh
  tools/commit-tests.sh
  tools/generate-hw-defs.sh
  tools/generate-yaml.sh
  tools/msys2_fetch_and_build_all.sh
Labels: hardware support

#4539 allow X10(/S) Express radio displays to actually dim, not just get slightly less blinding
  radio/src/targets/horus/board.h
Labels: enhancement ✨, UX-UI

#4540 Decrease backlight minimum for X10E on 2.9
  radio/src/targets/horus/board.h
Labels: enhancement ✨, UX-UI

#4551 fix(color): Slow performance of Manage Models page.
  radio/src/gui/colorlcd/model_select.cpp
Labels: color, bug/regression ↩️

#4478 feat(color): Use DMA for SPI flash access
  radio/src/drivers/frftl.cpp
  radio/src/drivers/frftl.h
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
  radio/src/targets/common/arm/stm32/diskio_spi.cpp
  radio/src/targets/common/arm/stm32/diskio_spi_flash.cpp
  radio/src/targets/common/arm/stm32/diskio_spi_flash.h
  radio/src/targets/common/arm/stm32/spi_flash.cpp
  radio/src/targets/common/arm/stm32/stm32_spi.cpp
  radio/src/targets/common/arm/stm32/stm32_spi.h
  radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/nv14/hal.h
  radio/src/targets/pl18/hal.h
Labels: enhancement ✨

#4520 fix: enable radio test for surface radio
  .github/workflows/actions.yml
  companion/src/CMakeLists.txt
  radio/src/dataconstants.h
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/128x64/view_main.cpp
  radio/src/gui/212x64/view_main.cpp
  radio/src/gui/colorlcd/input_edit_adv.cpp
  radio/src/input_mapping.h
  radio/src/lua/api_general.cpp
  radio/src/mixer.cpp
  radio/src/myeeprom.h
  radio/src/storage/yaml/CMakeLists.txt
  radio/src/storage/yaml/yaml_datastructs.cpp
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_x9lite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
  radio/src/tests/lua.cpp
  radio/src/tests/mixer.cpp
  radio/src/tests/sources.cpp
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/lua_inputs.jinja
  radio/util/hw_defs/yaml_inputs.jinja
  tools/commit-tests.sh
  tools/generate-hw-defs.sh
  tools/generate-yaml.sh
  tools/msys2_fetch_and_build_all.sh
Labels: bug 🪲, unit tests 🧪, user manual change

#4557 fix(color): Incorrect title for 'Delete label' progress bar popup.
  radio/src/gui/colorlcd/model_select.cpp
Labels: bug 🪲, color

#4560 fix(b&w): Cursor vanishes in switch section of hardware setup page.
  radio/src/gui/common/stdlcd/radio_hardware.cpp
Labels: B&W, bug/regression ↩️

#4555 fix(color): Popup for setting Trim in Input edit does not show any values.
  radio/src/gui/colorlcd/input_edit_adv.cpp
Labels: color, bug/regression ↩️

#4415 chore: Add support for UA language translation.
  companion/src/firmwares/opentx/opentxinterface.h
  companion/src/generaledit/generalsetup.cpp
  radio/src/CMakeLists.txt
  radio/src/fonts/lvgl/get_char_cyrillic.py
  radio/src/fonts/lvgl/lv_font_arimo_ua_13.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_16.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_24.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_9.c
  radio/src/fonts/lvgl/make_fonts.sh
  radio/src/fonts/sqt5/font_ua_04x06.png
  radio/src/fonts/sqt5/font_ua_05x07.png
  radio/src/fonts/sqt5/font_ua_08x10.png
  radio/src/fonts/sqt5/font_ua_10x14.png
  radio/src/fonts/std/font_ua_04x06.png
  radio/src/fonts/std/font_ua_05x07.png
  radio/src/fonts/std/font_ua_08x10.png
  radio/src/fonts/std/font_ua_10x14.png
  radio/src/gui/colorlcd/fonts.cpp
  radio/src/gui/common/stdlcd/fonts.cpp
  radio/src/gui/common/stdlcd/utf8.cpp
  radio/src/lv_conf.h
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tts_ua.cpp
  radio/src/translations/tw.h
  radio/src/translations/ua.h
  radio/util/font2png.py
Labels: translation

#4565 feat(bw128): Display sensor count when sensor list not expanded
  radio/src/gui/128x64/model_telemetry.cpp
Labels: UX-UI, B&W

#4554 feat(color): Add 'popup' option to GVARs for color LCD radios.
  radio/src/gui/colorlcd/model_gvars.cpp
  radio/src/gui/colorlcd/popups.cpp
  radio/src/gui/colorlcd/popups.h
  radio/src/gvars.cpp
  radio/src/gvars.h
  radio/src/main.cpp
  radio/src/opentx.cpp
Labels: color, UX-UI

#4524 feat(color): Add alternate layouts for model list in Manage Models page
  radio/src/bitmaps/480x272/default_theme/mask_model_grid_large.png
  radio/src/bitmaps/480x272/default_theme/mask_model_grid_small.png
  radio/src/bitmaps/480x272/default_theme/mask_model_list_one.png
  radio/src/bitmaps/480x272/default_theme/mask_model_list_two.png
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/bitmaps.cpp
  radio/src/gui/colorlcd/menus.h
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/gui/colorlcd/model_select.h
  radio/src/storage/modelslist.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
Labels: color, UX-UI

#4532 feat(color): Single select option for model labels plus label AND/OR filtering logic.
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/listbox.cpp
  radio/src/gui/colorlcd/listbox.h
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/gui/colorlcd/radio_setup.cpp
  radio/src/storage/modelslist.cpp
  radio/src/storage/modelslist.h
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x12s.cpp
  radio/src/thirdparty/libopenui/src/table.cpp
  radio/src/thirdparty/libopenui/src/table.h
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: color, UX-UI, user manual change

#4567 chore(ci): Bump action versions due to Node.js 16 EoL
  .github/workflows/actions.yml
  .github/workflows/linux_cpn.yml
  .github/workflows/macosx_cpn.yml
  .github/workflows/nightly.yml
  .github/workflows/win_cpn-32.yml
  .github/workflows/win_cpn-64.yml
Labels: ci/cd

#4577 fix(radio): Trainer SF properties not read correctly from YAML file.
  radio/src/storage/yaml/yaml_datastructs_funcs.cpp
Labels: bug 🪲

#4576 chore: Automate windows installer license copyright year
  companion/src/CMakeLists.txt
  companion/targets/windows/license.txt.in
Labels: companion, compilation

#4578 chore(cpn): Automate setting Companion Help About copyright year
  companion/src/CMakeLists.txt
  companion/src/mainwindow.cpp
  companion/src/version.h.in
Labels: companion, compilation

#4573 fix(cpn): QT lupdate gremlins in translations
  companion/src/generaledit/generalsetup.ui
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
Labels: companion, translation, bug/regression ↩️

#4563 fix: ADC EXT channel shifting on some ADC configuration
  radio/src/targets/common/arm/stm32/stm32_adc.cpp
  radio/src/targets/pl18/hal.h
Labels: bug 🪲
