Repository EdgeTX/edgetx, pull requests merged in 2024-03, with the labels that each got.

#4693 fix(lua): add 'repetition' property to getCustomFunction and setCustomFunction tables
  radio/src/lua/api_model.cpp
Labels: lua-api, bug/regression ↩️

#4691 fix(cpn): initialisation of log viewer x-axis should use log time, not system time
  companion/src/logsdialog.cpp
Labels: bug 🪲, companion

#4688 fix: grammatical errors in Ukrainian 🇺🇦 translation
  radio/src/fonts/lvgl/lv_font_arimo_ua_13.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_24.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_9.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_bold_16.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_bold_32.c
  radio/src/fonts/lvgl/lv_font_arimo_ua_bold_64.c
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/translations/ua.h
Labels: translation

#4686 fix(radio): invalid memory access if SpaceMouse input present but not supported
  radio/src/mixer.cpp
Labels: bug 🪲, compilation

#4684 fix(radio) fix -DUSBJ_EX=OFF issues
  radio/src/gui/128x64/model_setup.cpp
  radio/src/targets/common/arm/stm32/usb_driver.cpp
  radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
Labels: compilation, bug/regression ↩️

#4703 fix: add missing ua translation strings
  radio/src/translations/ua.h
Labels: translation

#4709 fix(b&w): Long ENTER not working correctly when using ADJUST GV SF
  radio/src/gui/128x64/model_special_functions.cpp
Labels: bug 🪲, UX-UI

#4393 feat(color): Run widget 'background' function while in setup pages.
  radio/src/gui/colorlcd/model_outputs.cpp
  radio/src/gui/colorlcd/page.cpp
  radio/src/gui/colorlcd/page.h
  radio/src/gui/colorlcd/radio_theme.cpp
  radio/src/gui/colorlcd/tabsgroup.cpp
  radio/src/gui/colorlcd/trainer_bluetooth.cpp
  radio/src/gui/colorlcd/view_main.cpp
  radio/src/gui/colorlcd/view_main.h
  radio/src/gui/colorlcd/widgets/widgets_container_impl.h
  radio/src/gui/colorlcd/widgets_container.h
Labels: widget, lua

#4714 fix(el18): SWB and SWD swapped
  radio/src/targets/nv14/hal.h
Labels: bug/regression ↩️

#4720 fix(telemetry): process DSM LIPO Cells Monitor sensor correctly
  radio/src/telemetry/spektrum.cpp
Labels: telemetry 📶

#4730 fix(cpn): Joystick pots, sliders and 6POS switch not working in simulator.
  companion/src/simulation/simulatorwidget.cpp
Labels: simulator, bug/regression ↩️

#4738 fix(tlite): default switch configuration wrong
  radio/util/hw_defs/switch_config.py
Labels: bug/regression ↩️

#4687 chore(cpn): simulators for EL18, TProV2, Pocket, T20
  companion/src/companion.qrc
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/images/simulator/JumperT20/bottom.png
  companion/src/images/simulator/JumperT20/left.png
  companion/src/images/simulator/JumperT20/right.png
  companion/src/images/simulator/JumperT20/top.png
  companion/src/images/simulator/Pocket/bottom.png
  companion/src/images/simulator/Pocket/left.png
  companion/src/images/simulator/Pocket/right.png
  companion/src/images/simulator/Pocket/top.png
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetJumperT20.cpp
  companion/src/simulation/simulateduiwidgetJumperT20.ui
  companion/src/simulation/simulateduiwidgetPocket.cpp
  companion/src/simulation/simulateduiwidgetPocket.ui
  companion/src/simulation/simulatorwidget.cpp
  radio/util/hw_defs/switch_config.py
  tools/build-companion.sh
Labels: simulator

#4701 feat: support Jumper T20 V2
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  companion/src/CMakeLists.txt
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  fw.json
  radio/src/datastructs.h
  radio/src/gui/128x64/startup_shutdown.cpp
  radio/src/hal/rotary_encoder.h
  radio/src/storage/yaml/CMakeLists.txt
  radio/src/storage/yaml/yaml_datastructs.cpp
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/usb_descriptor.h
  radio/src/telemetry/crossfire.h
  radio/util/hw_defs/legacy_names.py
  radio/util/hw_defs/pot_config.py
  radio/util/hw_defs/switch_config.py
  tools/build-companion.sh
  tools/build-gh.sh
  tools/commit-tests.sh
  tools/generate-hw-defs.sh
  tools/generate-yaml.sh
  tools/msys2_fetch_and_build_all.sh
Labels: hardware support

#4741 fix(cpn): Keys do not work in simulator for T-Lite, T12 and LR3PRO
  companion/src/simulation/simulateduiwidgetJumperT12.cpp
  companion/src/simulation/simulateduiwidgetJumperTLITE.cpp
  companion/src/simulation/simulateduiwidgetLR3PRO.cpp
Labels: simulator, bug/regression ↩️

#4704 feat: companion support for Jumper T14
  .github/ISSUE_TEMPLATE/bug-report.yml
  companion/src/CMakeLists.txt
  companion/src/companion.qrc
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/opentx/opentxinterface.cpp
  companion/src/images/simulator/JumperT14/bottom.png
  companion/src/images/simulator/JumperT14/left.png
  companion/src/images/simulator/JumperT14/right.png
  companion/src/images/simulator/JumperT14/top.png
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/simulateduiwidget.h
  companion/src/simulation/simulateduiwidgetJumperT14.cpp
  companion/src/simulation/simulateduiwidgetJumperT14.ui
  companion/src/simulation/simulatorwidget.cpp
  tools/build-companion.sh
Labels: companion, simulator

#4744 fix(b&w): ENTER key does not work on main view for T12, T-Lite and LR3PRO
  radio/src/gui/128x64/view_main.cpp
Labels: B&W, bug/regression ↩️

#4747 fix: issue in copy in BW mixer screen
  radio/src/gui/common/stdlcd/model_mixes.cpp
Labels: B&W, bug/regression ↩️

#4613 chore: translation catchup for v2.10
  companion/src/CMakeLists.txt
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
  radio/src/fonts/lvgl/lv_font_noto_cn_13.c
  radio/src/fonts/lvgl/lv_font_noto_cn_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_24.c
  radio/src/fonts/lvgl/lv_font_noto_cn_9.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_cn_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/opentx.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: bug 🪲, companion, translation, house keeping 🧹

#4746 fix(cpn): battery level incorrect in simulator for B&W radios
  radio/src/targets/simu/adc_driver.cpp
Labels: simulator, bug/regression ↩️

#4751 fix(bw): SF Play Value parameter display clipped on 128x64 B&W
  radio/src/gui/128x64/model_special_functions.cpp
Labels: UX-UI, B&W, bug/regression ↩️

#4753 chore: formatting of telemetry structs for readability
  radio/src/telemetry/crossfire.cpp
  radio/src/telemetry/flysky_ibus.cpp
  radio/src/telemetry/flysky_nv14.cpp
  radio/src/telemetry/frsky_sport.cpp
  radio/src/telemetry/ghost.cpp
  radio/src/telemetry/hitec.cpp
  radio/src/telemetry/hott.cpp
  radio/src/telemetry/mlink.cpp
  radio/src/telemetry/spektrum.cpp
Labels: documentation

#4760 fix(cpn): DK wrong translation
  companion/src/translations/companion_da.ts
Labels: companion, translation

#4776 fix(cpn): T20V2 simulator uses the 9X UI in Companion.
  companion/src/simulation/simulatorwidget.cpp
Labels: bug 🪲, simulator

#4771 chore: redefinition warning for `INTMODULE_BOOTCMD_GPIO`
  radio/src/targets/taranis/hal.h
Labels: compilation

#4779 fix(cpn): screen colors in simulator for B&W OLED radios
  companion/src/images/simulator/JumperTPRO/bottom.png
  companion/src/images/simulator/JumperTPRO/left.png
  companion/src/images/simulator/JumperTPRO/right.png
  companion/src/images/simulator/JumperTPRO/top.png
  companion/src/images/simulator/LR3PRO/bottom.png
  companion/src/images/simulator/LR3PRO/top.png
  companion/src/simulation/simulateduiwidgetJumperT20.cpp
  companion/src/simulation/simulateduiwidgetJumperTPRO.cpp
  companion/src/simulation/simulateduiwidgetJumperTPRO.ui
  companion/src/simulation/simulateduiwidgetLR3PRO.cpp
  companion/src/simulation/simulateduiwidgetLR3PRO.ui
  companion/src/simulation/widgets/lcdwidget.cpp
  companion/src/simulation/widgets/lcdwidget.h
Labels: simulator

#4772 chore: translation updates for PT
  radio/src/translations/pt.h
Labels: translation

#4697 feat(color): make warning for serial port voltage levels clearer
  radio/src/fonts/lvgl/lv_font_noto_jp_13.c
  radio/src/fonts/lvgl/lv_font_noto_jp_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_24.c
  radio/src/fonts/lvgl/lv_font_noto_jp_9.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_jp_bold_32.c
  radio/src/fonts/lvgl/lv_font_noto_tw_13.c
  radio/src/fonts/lvgl/lv_font_noto_tw_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_24.c
  radio/src/fonts/lvgl/lv_font_noto_tw_9.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_16.c
  radio/src/fonts/lvgl/lv_font_noto_tw_bold_32.c
  radio/src/gui/colorlcd/hw_serial.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: color, needs:translation

#4781 fix(color): displayed image not always cleared when changing folder in SD browser
  radio/src/gui/colorlcd/file_browser.cpp
Labels: bug 🪲, color

#4780 fix(bw): USB popup menu may not close.
  radio/src/main.cpp
Labels: bug 🪲, B&W

#4788 fix(mt12): bootloader startup uses wrong trim switch direction.
  radio/src/targets/common/arm/stm32/bootloader/boot.cpp
Labels: bug/regression ↩️

#4787 fix(b&w): dial/slider bars can overlap on main view
  radio/src/gui/128x64/view_main.cpp
Labels: bug 🪲, UX-UI, B&W

#4777 chore: Do not display trims position when trim is set as 3POS
  radio/src/gui/128x64/view_main.cpp
  radio/src/gui/212x64/view_main.cpp
  radio/src/gui/colorlcd/layouts/trims.cpp
Labels: bug 🪲, UX-UI

#4775 fix(cpn): llvm clang dll filename change breaking libsimulator builds
  radio/util/find_clang.py
Labels: companion, compilation, not-our-bug

#4735 fix(cpn): application crash, binary load error and binary source value mapping inconsistencies
  companion/src/firmwares/opentx/opentxeeprom.cpp
Labels: companion, bug/regression ↩️

#4774 fix(cpn): multi protocol and sd card updates
  companion/src/updates/repo.cpp
  companion/src/updates/repoassets.cpp
  companion/src/updates/updatemultiprotocol.cpp
  companion/src/updates/updatenetwork.cpp
  companion/src/updates/updatenetwork.h
Labels: bug 🪲, companion

#4793 feat: allow configuration of auto dimming for OLED screen
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/common/stdlcd/features.h
Labels: B&W

#4768 fixcpn): use model semver over radio semver for decoding model sources and switches
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  companion/src/firmwares/edgetx/yaml_rawsource.cpp
  companion/src/firmwares/edgetx/yaml_rawswitch.cpp
Labels: companion, bug/regression ↩️

#4794 fix(cpn): model semver check inc model name in warning msg
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
Labels: bug 🪲, companion

#4778 fix(bw): display GVar name if exist in telemetry screen
  radio/src/gui/128x64/view_telemetry.cpp
  radio/src/gui/212x64/view_telemetry.cpp
Labels: bug 🪲, B&W

#4804 fix(cpn): allow PPM and SBUS on external rf standard size module
  companion/src/firmwares/moduledata.cpp
Labels: companion, bug/regression ↩️

#4801 chore(cpn): add Accept and Decline buttons to yaml decode unsupported versions dialogs
  companion/src/constants.h
  companion/src/firmwares/edgetx/yaml_generalsettings.cpp
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
Labels: enhancement ✨, companion

#4767 feat(color): show FM name and number in GV edit page
  radio/src/gui/colorlcd/model_gvars.cpp
Labels: color, UX-UI

#4770 feat: only allow flash when target matches
  radio/src/io/bootloader_flash.cpp
  radio/src/targets/horus/bootloader/boot_menu.cpp
  radio/src/targets/nv14/bootloader/boot_menu.cpp
  radio/src/targets/pl18/bootloader/boot_menu.cpp
  radio/src/targets/taranis/bootloader/boot_menu.cpp
Labels: enhancement ✨, UX-UI, user manual change

#4733 fix(telemetry): frsky angles should be be signed (allow negative)
  radio/src/telemetry/frsky_sport.cpp
Labels: telemetry 📶

#4809 fix: custom switches startup position need to be loaded on model change
  radio/src/storage/storage_common.cpp
Labels: bug 🪲

#4806 fix(bw): missing PT special chars handling
  radio/src/fonts/sqt5/font_pt_04x06.png
  radio/src/fonts/std/font_pt_04x06.png
  radio/src/gui/128x64/lcd.cpp
  radio/src/gui/212x64/lcd.cpp
  radio/src/gui/common/stdlcd/utf8.cpp
Labels: bug 🪲, translation

#4810 chore: PT translation update with special characters
  radio/src/translations/pt.h
Labels: translation

#4815 fix: Stack overflow in some non-English language versions.
  radio/src/gui/gui_common.cpp
Labels: bug 🪲, house keeping 🧹

#4821 fix(pt): broken quick menu, minor tweaks
  radio/src/translations/pt.h
Labels: bug 🪲, translation

#4816 fix(bw): language special characters not working for 10x14 font size
  radio/src/gui/128x64/lcd.cpp
  radio/src/gui/128x64/lcd.h
  radio/src/gui/212x64/lcd.cpp
  radio/src/gui/212x64/lcd.h
  radio/src/gui/common/stdlcd/fonts.cpp
  radio/src/gui/common/stdlcd/fonts.h
  radio/src/gui/common/stdlcd/utf8.cpp
Labels: translation, bug/regression ↩️

#4708 fix: allow compilation of BW radio when DEBUG=Y
  radio/src/CMakeLists.txt
  radio/src/targets/common/arm/CMakeLists.txt
  radio/src/targets/common/arm/stm32/CMakeLists.txt
  radio/src/targets/common/arm/stm32/bootloader/CMakeLists.txt
Labels: compilation

#4783 chore: remove unused USBD_StringSerial
  radio/src/targets/common/arm/stm32/usbd_desc.c
  radio/src/targets/common/arm/stm32/usbd_desc.h
Labels: house keeping 🧹

#4823 fix(bw): add missing UA characters, mapping
  radio/src/fonts/std/font_ua_04x06.png
  radio/src/fonts/std/font_ua_05x07.png
  radio/src/fonts/std/font_ua_08x10.png
  radio/src/fonts/std/font_ua_10x14.png
  radio/src/gui/common/stdlcd/utf8.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/util/font2png.py
Labels: bug 🪲, B&W, translation

#4827 refactor: FLASH size optimisations for B&W.
  radio/src/bitmaps/128x64/asterisk.png
  radio/src/bitmaps/128x64/sleep.png
  radio/src/definitions.h
  radio/src/gui/128x64/menu_model.cpp
  radio/src/gui/128x64/menu_radio.cpp
  radio/src/gui/128x64/menus.h
  radio/src/gui/128x64/model_curve_edit.cpp
  radio/src/gui/128x64/model_failsafe.cpp
  radio/src/gui/128x64/model_outputs.cpp
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/128x64/popups.cpp
  radio/src/gui/128x64/startup_shutdown.cpp
  radio/src/gui/128x64/view_main.cpp
  radio/src/gui/212x64/model_curve_edit.cpp
  radio/src/gui/212x64/model_gvars.cpp
  radio/src/gui/212x64/model_outputs.cpp
  radio/src/gui/212x64/model_telemetry.cpp
  radio/src/gui/212x64/view_main.cpp
  radio/src/gui/common/stdlcd/model_inputs.cpp
  radio/src/gui/common/stdlcd/model_mixes.cpp
  radio/src/gui/common/stdlcd/model_setup_pxx2.cpp
  radio/src/gui/common/stdlcd/popups.cpp
  radio/src/gui/common/stdlcd/popups.h
  radio/src/gui/common/stdlcd/view_telemetry.cpp
  radio/src/gui/gui_common.cpp
  radio/src/gui/gui_common.h
  radio/src/main.cpp
  radio/src/opentx.cpp
  radio/src/opentx.h
  radio/src/pulses/modules_helpers.cpp
  radio/src/pulses/modules_helpers.h
  radio/src/storage/yaml/yaml_bits.cpp
  radio/src/storage/yaml/yaml_node.h
  radio/src/telemetry/frsky_d.cpp
  radio/src/telemetry/frsky_sport.cpp
  radio/util/hw_defs/hal_adc_inputs.jinja
Labels: compilation, house keeping 🧹
