Repository EdgeTX/edgetx, pull requests merged in 2024-04, with the labels that each got.

#4829 fix(lua): add missing EVT_PAGEDN_xxx events for Lua
  radio/util/hw_defs/lua_keys.jinja
Labels: lua, bug/regression ↩️

#4833 fix(lua): ignore potential unwanted key events
  radio/src/lua/interface.cpp
  radio/src/main.cpp
Labels: bug 🪲, lua

#4728 fix(telemetry): temperature UNIT conversion when temperature has decimals
  radio/src/gui/128x64/model_telemetry_sensor.cpp
  radio/src/gui/212x64/model_telemetry_sensor.cpp
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/telemetry/telemetry_sensors.cpp
Labels: telemetry 📶

#4758 chore(radio): reduce USB string buffer by 414 bytes
  radio/src/targets/common/arm/stm32/usbd_conf.h
Labels: house keeping 🧹

#4602 feat: add battery level reporting to USB HID joystick
  radio/src/usb_joystick.cpp
Labels: enhancement ✨

#4745 feat(color): move ADC Filter and Center Beep settings to 'Other' page
  radio/src/gui/colorlcd/model_setup.cpp
  radio/src/gui/colorlcd/preflight_checks.cpp
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/pl.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
Labels: color, UX-UI

#4726 fix(radio): usb joystick descriptor, unusable joystick axis
  radio/src/targets/common/arm/stm32/usbd_hid_joystick.c
Labels: bug 🪲

#4850 fix: GV9 missing on FM0 when trims > 4
  radio/src/gui/128x64/model_flightmodes.cpp
Labels: B&W, bug/regression ↩️

#4846 feat(color): adjust top bar widget sizes.
  radio/src/gui/colorlcd/layouts/topbar_impl.cpp
  radio/src/gui/colorlcd/topbar.h
  radio/src/gui/colorlcd/widgets/radio_info.cpp
Labels: color, widget

#4694 feat(color): warning when duplicating theme if name exists
  radio/src/gui/colorlcd/radio_theme.cpp
  radio/src/gui/colorlcd/theme_manager.cpp
  radio/src/targets/simu/simufatfs.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: bug 🪲, enhancement ✨, color, UX-UI

#4689 feat: add U-BLOX GPS support
  radio/src/gps.cpp
  radio/src/gps.h
  radio/src/gps_nmea.cpp
  radio/src/gps_nmea.h
  radio/src/gps_ubx.cpp
  radio/src/gps_ubx.h
  radio/src/serial.cpp
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/simu/CMakeLists.txt
  radio/src/targets/simu/rs232-linux.c
  radio/src/targets/simu/rs232-win.c
  radio/src/targets/simu/rs232.h
  radio/src/targets/simu/simpgmspace.cpp
Labels: enhancement ✨, contest

#4862 fix(color): crash in SF list when using CN or TW translations.
  radio/src/gui/colorlcd/special_functions.cpp
Labels: bug 🪲, color

#4863 fix(cpn): Mac Companion build error on Github.
  radio/src/gui/colorlcd/layouts/sliders.cpp
Labels: ci/cd, companion, compilation

#4857 feat(radio): prefer UBX over NMEA when both supported
  radio/src/gps.cpp
  radio/src/gps_ubx.cpp
Labels: enhancement ✨

#4865 fix(color): restore previous startup and shutdown functionality.
  radio/src/gui/colorlcd/startup_shutdown.cpp
  radio/src/opentx.cpp
  radio/src/tasks.cpp
Labels: color, bug/regression ↩️

#4871 fix: pxx2 can transport 24 chans
  radio/src/pulses/pxx2.cpp
  radio/src/pulses/pxx2.h
  radio/src/telemetry/frsky_pxx2.cpp
Labels: bug 🪲

#4866 fix(de): bootloader translations too long
  radio/src/translations/de.h
Labels: bug 🪲, B&W, translation

#4851 chore(radio): cleanup -Wzero-as-null-pointer-constant warnings
  radio/src/audio.h
  radio/src/bin_allocator.cpp
  radio/src/bin_allocator.h
  radio/src/cli.cpp
  radio/src/gui/navigation/common.cpp
  radio/src/hal/fatfs_diskio.cpp
  radio/src/logs.cpp
  radio/src/lua/interface.cpp
  radio/src/opentx.h
  radio/src/pulses/crossfire.cpp
  radio/src/rtos.h
  radio/src/sdcard.cpp
  radio/src/targets/common/arm/stm32/audio_dac_driver.cpp
  radio/src/targets/common/arm/stm32/bootloader/bin_files.cpp
  radio/src/targets/common/arm/stm32/sdcard_spi.cpp
  radio/src/targets/common/arm/stm32/stm32_exti_driver.cpp
  radio/src/targets/common/arm/stm32/stm32_spi.cpp
Labels: compilation, house keeping 🧹

#4853 chore(radio): cleanup -Wundef compiler warnings
  radio/src/dataconstants.h
  radio/src/targets/common/arm/stm32/stm32_hal_ll.h
  radio/src/targets/common/arm/stm32/usbd_msc_conf.h
Labels: compilation, house keeping 🧹

#4905 chore(t14): remove unused ws2812
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/hal.h
Labels: hardware support, partner, house keeping 🧹

#4901 chore(color): display mixer period in statistic screen
  radio/src/gui/colorlcd/view_statistics.cpp
Labels: color

#4892 fix(t14): charge led sometimes pink at USB connection
  radio/src/targets/taranis/board.cpp
Labels: bug 🪲, partner

#4891 fix(pl18): USB detect pin can be uninitialized in bootloader
  radio/src/targets/pl18/board.cpp
  radio/src/targets/pl18/board.h
Labels: bug 🪲

#4884 fix(bw): multiple issues with menu navigation for 9X type radios
  radio/src/gui/128x64/model_flightmodes.cpp
  radio/src/gui/128x64/model_select.cpp
  radio/src/gui/common/stdlcd/menus.cpp
  radio/src/gui/common/stdlcd/menus.h
  radio/src/gui/navigation/navigation_9x.cpp
  radio/src/keys.h
  radio/src/main.cpp
Labels: bug/regression ↩️

#4917 fix: menu up/down on 9x nav
  radio/src/keys.h
Labels: B&W, bug/regression ↩️

#4918 feat(color): missing scroll bar on model template select pages.
  radio/src/gui/colorlcd/model_templates.cpp
Labels: bug 🪲, color, UX-UI

#4921 chore: all Chinese main menu items on one line
  radio/src/translations/cn.h
Labels: color, translation

#4886 fix(color): personal templates saved to wrong folder
  radio/src/gui/colorlcd/model_select.cpp
  radio/src/sdcard.h
Labels: bug/regression ↩️

#4919 fix(color): extra sliders and trims on main view after creating a new model.
  radio/src/storage/sdcard_common.cpp
Labels: bug 🪲, color, UX-UI

#4902 fix(cpn): T-Pro function switches
  companion/src/firmwares/edgetx/yaml_rawswitch.cpp
Labels: companion, bug/regression ↩️, blocks-release

#4861 chore(color): Lvgl performance improvements.
  cmake/Macros.cmake
  radio/src/gui/colorlcd/CMakeLists.txt
  radio/src/gui/colorlcd/input_mix_button.cpp
  radio/src/gui/colorlcd/input_mix_button.h
  radio/src/gui/colorlcd/input_mix_group.cpp
  radio/src/gui/colorlcd/input_mix_group.h
  radio/src/gui/colorlcd/list_line_button.cpp
  radio/src/gui/colorlcd/list_line_button.h
  radio/src/gui/colorlcd/mixer_edit_adv.cpp
  radio/src/gui/colorlcd/model_flightmodes.cpp
  radio/src/gui/colorlcd/model_gvars.cpp
  radio/src/gui/colorlcd/model_inputs.cpp
  radio/src/gui/colorlcd/model_inputs.h
  radio/src/gui/colorlcd/model_logical_switches.cpp
  radio/src/gui/colorlcd/model_mixes.cpp
  radio/src/gui/colorlcd/model_mixes.h
  radio/src/gui/colorlcd/model_outputs.cpp
  radio/src/gui/colorlcd/model_telemetry.cpp
  radio/src/gui/colorlcd/special_functions.cpp
  radio/src/gui/colorlcd/view_main.cpp
  radio/src/gui/colorlcd/view_main.h
  radio/src/gui/colorlcd/widget.cpp
  radio/src/gui/colorlcd/widget.h
Labels: color, UX-UI

#4922 fix: t20v2 use 1M flash MCU
  radio/src/targets/taranis/CMakeLists.txt
Labels: hardware support, partner

#4932 chore(color): remove unused pl18/libopenui_config.h
  radio/src/targets/pl18/libopenui_config.h
Labels: house keeping 🧹

#4935 fix(bw): screen shots saved on radios with OLED screens inverted
  radio/src/gui/screenshot.cpp
Labels: B&W

#4931 fix(color): mixes list view not resizing when mixer monitors enabled
  radio/src/gui/colorlcd/list_line_button.h
  radio/src/gui/colorlcd/model_mixes.cpp
Labels: color, UX-UI, bug/regression ↩️

#4870 feat(lua): add 'mkdir' and 'rename' functions
  radio/src/lua/api_filesystem.cpp
  radio/src/lua/api_general.cpp
  radio/src/targets/simu/simufatfs.cpp
Labels: lua-api

#4945 chore: remove unused PWM_BACKLIGHT define
  radio/src/gui/128x64/radio_setup.cpp
  radio/src/gui/common/stdlcd/features.h
  radio/src/opentx.cpp
  radio/src/translations.cpp
  radio/src/translations.h
Labels: house keeping 🧹

#4943 fix(color): don't enlarge image in the file preview window.
  radio/src/gui/colorlcd/file_preview.cpp
  radio/src/thirdparty/libopenui/src/static.cpp
  radio/src/thirdparty/libopenui/src/static.h
Labels: color, bug/regression ↩️
