Repository EdgeTX/edgetx, pull requests merged in 2024-12, with the labels that each got.

#5686 feat: use RTC backup for EM on BW F4 1Mb flash radio
  radio/src/main.cpp
  radio/src/targets/taranis/CMakeLists.txt
Labels: B&W, bug/regression ↩️, firmware

#5617 chore: bump to macos-13
  .github/workflows/macosx_cpn.yml
Labels: companion, compilation

#5689 feat: S.Port telemetry for PPM/SBUS external module
  companion/src/firmwares/edgetx/yaml_moduledata.cpp
  companion/src/firmwares/moduledata.cpp
  companion/src/firmwares/moduledata.h
  companion/src/modeledit/setup_module.cpp
  companion/src/modelprinter.cpp
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/colorlcd/module/module_setup.cpp
  radio/src/pulses/modules_constants.h
  radio/src/pulses/ppm.cpp
  radio/src/pulses/pxx1.cpp
  radio/src/pulses/sbus.cpp
  radio/src/telemetry/frsky.cpp
  radio/src/telemetry/frsky.h
  radio/src/telemetry/multi.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/untranslated.h
Labels: enhancement ✨

#5701 fix(v16): Rework 6pos logic fix #5699 by proper init adcValues
  radio/src/hal/adc_driver.cpp
  radio/src/targets/horus/board.cpp
Labels: bug 🪲

#5706 fix(gx12): gimbal type typo
  radio/src/targets/taranis/CMakeLists.txt
Labels: bug 🪲

#5584 feat(simu): cross-platform connection of host serial ports to simu radio
  cmake/QtDefs.cmake
  companion/src/CMakeLists.txt
  companion/src/simulation/CMakeLists.txt
  companion/src/simulation/hostserialconnector.cpp
  companion/src/simulation/hostserialconnector.h
  companion/src/simulation/serialportsdialog.cpp
  companion/src/simulation/serialportsdialog.h
  companion/src/simulation/serialportsdialog.ui
  companion/src/simulation/simulatorinterface.h
  companion/src/simulation/simulatormainwindow.cpp
  companion/src/simulation/simulatormainwindow.h
  companion/src/simulation/simulatormainwindow.ui
  companion/src/simulation/simulatorwidget.h
  radio/src/targets/simu/CMakeLists.txt
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/targets/simu/opentxsimulator.h
  radio/src/targets/simu/rs232-linux.c
  radio/src/targets/simu/rs232-win.c
  radio/src/targets/simu/rs232.h
  radio/src/targets/simu/simpgmspace.cpp
  tools/setup_buildenv_ubuntu20.04.sh
  tools/setup_buildenv_ubuntu22.04.sh
Labels: simulator, contest

#5715 feat(color): only use red background for alert screens
  radio/src/gui/colorlcd/libui/fullscreen_dialog.cpp
Labels: color, UX-UI

#5719 chore(cpn): remove compiler warnings
  companion/src/firmwares/boardjson.cpp
  companion/src/firmwares/modeldata.cpp
Labels: companion, compilation, house keeping 🧹

#5718 chore(cpn): remove unused binary general settings fields
  companion/src/firmwares/generalsettings.cpp
  companion/src/firmwares/generalsettings.h
Labels: companion, bug/regression ↩️, house keeping 🧹

#5714 fix(color): rotary encoder events not always working on some screens
  radio/src/gui/colorlcd/libui/table.cpp
  radio/src/gui/colorlcd/libui/table.h
Labels: color, UX-UI, bug/regression ↩️

#5688 feat(lua): add getter/setter for Global Variable details
  radio/src/lua/api_model.cpp
Labels: lua-api

#5722 fix(bumblebee): customisable switches display issue, audio mute not working
  radio/src/gui/128x64/model_setup.cpp
  radio/src/targets/taranis/hal.h
Labels: bug/regression ↩️

#5725 fix(color): potential crash when changing screen layout
  radio/src/gui/colorlcd/libui/table.cpp
Labels: color, UX-UI, bug/regression ↩️

#5730 fix(color): VCENTER does not work for Lua drawText function
  radio/src/lua/api_colorlcd.cpp
Labels: color, UX-UI, bug/regression ↩️

#5727 fix(bw): roller needs two clicks to move past model setup 'Customisable Switches' line
  radio/src/gui/128x64/model_setup.cpp
Labels: UX-UI, B&W, bug/regression ↩️

#5716 fix(radio): writing of .luac files can fail on some radios
  radio/src/lua/interface.cpp
Labels: enhancement ✨

#5717 feat(bw): make more RAM available to Lua scripts on some radios
  radio/src/bin_allocator.cpp
  radio/src/bin_allocator.h
  radio/src/edgetx.cpp
Labels: enhancement ✨, B&W, lua

#5721 feat: dramatically reduce SDcard access while in Tools screen
  radio/src/edgetx.h
  radio/src/gui/common/stdlcd/radio_tools.cpp
Labels: enhancement ✨, house keeping 🧹

#5733 fix(bw): incorrect characters displayed for pre-flight checks
  radio/src/fonts/sqt5/font_04x06_extra.png
  radio/src/fonts/sqt5/font_05x07_extra.png
  radio/src/fonts/sqt5/font_10x14_extra.png
  radio/src/fonts/std/font_04x06_extra.png
  radio/src/fonts/std/font_05x07_extra.png
  radio/src/fonts/std/font_10x14_extra.png
  radio/src/gui/common/stdlcd/fonts.h
  radio/src/translations/cz.h
Labels: UX-UI, B&W, bug/regression ↩️

#5732 fix(radio): potential crash when writing .luac files
  radio/src/lua/interface.cpp
Labels: color, B&W, bug/regression ↩️

#5740 fix(color): channel monitor crash when changing from logical switch view
  radio/src/gui/colorlcd/mainview/view_logical_switches.cpp
Labels: color, bug/regression ↩️

#5263 chore: update GNU Arm toolchain to 14.2.rel1
  cmake/toolchain/arm-none-eabi.cmake
  radio/src/CMakeLists.txt
  radio/src/bin_allocator.cpp
  radio/src/boards/generic_stm32/aux_ports.cpp
  radio/src/storage/yaml/yaml_node.h
  radio/src/syscalls.c
  tools/setup_buildenv_msys2_stage2.sh
  tools/setup_buildenv_ubuntu20.04.sh
  tools/setup_buildenv_ubuntu22.04.sh
Labels: compilation
