Repository EdgeTX/edgetx, pull requests merged in 2025-06, with the labels that each got.

#6340 fix(f2): DMA buffer alignment
  radio/src/targets/common/arm/stm32/f2/memory_sections.h
Labels: bug/regression ↩️

#6321 refactor(radio): move per10ms() to a software timer
  radio/src/bootloader/boot_dfu.cpp
  radio/src/bootloader/boot_menu.cpp
  radio/src/bootloader/boot_uf2.cpp
  radio/src/edgetx.cpp
  radio/src/targets/common/arm/stm32/timers_driver.cpp
  radio/src/tasks.cpp
Labels: enhancement ✨, house keeping 🧹

#6354 fix(color): choice button display not updating if values list changed
  radio/src/gui/colorlcd/libui/choice.cpp
Labels: color, UX-UI, bug/regression ↩️

#6357 fix(lua): curve value incorrect in model.getInput and model.insertInput API calls
  radio/src/datastructs_private.h
  radio/src/gui/common/stdlcd/model_curves.cpp
  radio/src/lua/api_model.cpp
Labels: UX-UI, lua-api, B&W, bug/regression ↩️

#6348 chore: SE translation updates
  companion/src/translations/companion_sv.ts
  radio/src/translations/se.h
Labels: translation

#6337 fix(color): fix EM crashes when shutting down Lua states
  radio/src/edgetx.cpp
  radio/src/gui/colorlcd/standalone_lua.cpp
  radio/src/lua/interface.cpp
  radio/src/lua/lua_api.h
  radio/src/lua/widgets.cpp
  radio/src/mixer.cpp
  radio/src/tests/lua.cpp
  radio/src/thirdparty/Lua/src/lstate.c
Labels: color, lua, bug/regression ↩️

#6310 fix(h7): improved data cache maintenance
  radio/src/targets/common/arm/stm32/diskio_sdio.cpp
  radio/src/targets/st16/lcd_driver.cpp
Labels: house keeping 🧹

#6343 fix(color): outputs widget channel value may not update if units is set to μs
  radio/src/gui/colorlcd/widgets/outputs.cpp
Labels: color, UX-UI, bug/regression ↩️

#6359 feat(debug): add a cli option for testing SD though fatFS
  radio/src/cli.cpp
Labels: debug

#6358 fix(gx12): use PCA95xx reset pin in case of read issues
  radio/src/targets/taranis/gx12/bsp_io.cpp
Labels: bug 🪲

#6345 fix(v14): ADC RTC battery reading returns strange value
  radio/src/targets/taranis/hal.h
Labels: bug 🪲

#6338 fix(v14): SA/SD LED init
  radio/src/targets/taranis/board.cpp
  radio/src/targets/taranis/hal.h
Labels: bug 🪲

#6372 fix(lua): memory leak when re-loading Lua scripts
  radio/src/lua/interface.cpp
Labels: color, B&W, lua, bug/regression ↩️

#6375 fix(color): incorrect portrait layout for radio hardware page
  radio/src/gui/colorlcd/radio/radio_hardware.cpp
Labels: color, UX-UI, bug/regression ↩️

#6373 fix(radio): do not mask inputs if PWM gimbal detection failed
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/horus/hal.h
Labels: bug/regression ↩️

#6377 fix(color): UI freeze when setting up 'Set' special function with no timers configured
  radio/src/gui/128x64/model_special_functions.cpp
  radio/src/gui/212x64/model_special_functions.cpp
  radio/src/gui/colorlcd/model/special_functions.cpp
  radio/src/gui/gui_common.cpp
  radio/src/gui/gui_common.h
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/ko.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: bug 🪲, color, UX-UI

#6378 fix(cpn): length of widget option strings
  companion/src/firmwares/customisation_data.h
Labels: bug 🪲, companion

#6382 fix(cpn): units for special telemetry (Batt, Time, GPS)
  companion/src/firmwares/rawsource.cpp
Labels: bug 🪲, companion

#6388 chore: update YAML files.
  radio/src/storage/yaml/yaml_datastructs_128x64.cpp
  radio/src/storage/yaml/yaml_datastructs_f16.cpp
  radio/src/storage/yaml/yaml_datastructs_gx12.cpp
  radio/src/storage/yaml/yaml_datastructs_nb4p.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14_family.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
  radio/src/storage/yaml/yaml_datastructs_pl18u.cpp
  radio/src/storage/yaml/yaml_datastructs_st16.cpp
  radio/src/storage/yaml/yaml_datastructs_t15.cpp
  radio/src/storage/yaml/yaml_datastructs_t20.cpp
  radio/src/storage/yaml/yaml_datastructs_tpro.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
  radio/src/storage/yaml/yaml_datastructs_x9d.cpp
  radio/src/storage/yaml/yaml_datastructs_x9dp2019.cpp
  radio/src/storage/yaml/yaml_datastructs_x9e.cpp
  radio/src/storage/yaml/yaml_datastructs_xlite.cpp
  radio/src/storage/yaml/yaml_datastructs_xlites.cpp
Labels: color, B&W, house keeping 🧹

#6389 fix(sim): flex switches may be set incorrectly on startup
  radio/src/targets/simu/simpgmspace.cpp
Labels: bug 🪲, color, B&W, simulator

#6390 fix(color): switch picker for Lua scripts may show incorrect switch names
  radio/src/gui/gui_common.cpp
Labels: bug 🪲, color, lua-api
