Repository EdgeTX/edgetx, pull requests merged in 2025-09, with the labels that each got.

#6562 fix(radio): use correct flash size instead of 2MB
  radio/src/bootloader/boot_uf2.cpp
  radio/src/drivers/uf2_ghostfat.cpp
  radio/src/drivers/uf2_ghostfat.h
Labels: bug 🪲

#6571 fix: pushCS should not be a GF
  companion/src/firmwares/boardjson.cpp
  companion/src/firmwares/boardjson.h
  companion/src/firmwares/boards.cpp
  companion/src/firmwares/boards.h
  companion/src/firmwares/customfunctiondata.cpp
  companion/src/firmwares/edgetx/yaml_customfunctiondata.cpp
  radio/src/gui/gui_common.cpp
Labels: bug 🪲

#6572 fix(tx15): 3POS not working for SE/SF
  radio/src/boards/rm-h750/bsp_io.cpp
  radio/src/targets/tx15/hal.h
Labels: bug 🪲

#6589 fix(tx15): unable to enter bootloader after #6585
  radio/src/boards/rm-h750/board.cpp
Labels: bug/regression ↩️

#6590 fix(color): source picker may show invalid switches
  radio/src/boards/generic_stm32/switches.cpp
  radio/src/targets/simu/switch_driver.cpp
Labels: color, UX-UI, bug/regression ↩️

#6588 feat(cpn): improve flashing messages
  companion/src/flash/flashfirmwaredialog.cpp
  companion/src/flash/process_sync.h
  companion/src/flash/radiointerface.cpp
  companion/src/flash/radiointerface.h
  companion/src/mainwindow.cpp
  companion/src/progress/progresswidget.cpp
  companion/src/progress/progresswidget.h
  companion/src/storage/firmwareinterface.cpp
Labels: companion, house keeping 🧹

#6604 fix(firmware): default customizable switches to be like classic 6POS
  radio/src/model_init.cpp
Labels: bug/regression ↩️, firmware

#6606 fix(doc): indicate setCFSLedColor() introduction date
  radio/src/lua/api_general.cpp
Labels: documentation, house keeping 🧹

#6607 chore(cpn): set default for CFS to mimic 6POS.
  companion/src/firmwares/modeldata.cpp
Labels: companion, house keeping 🧹

#6116 chore(flysky): clean up unused nv14 target
  radio/src/CMakeLists.txt
  radio/src/boards/generic_stm32/module_ports.cpp
  radio/src/datastructs.h
  radio/src/datastructs_private.h
  radio/src/gui/colorlcd/model/menu_model.cpp
  radio/src/gui/colorlcd/module/afhds2a_settings.cpp
  radio/src/gui/colorlcd/module/afhds2a_settings.h
  radio/src/gui/colorlcd/radio/radio_version.cpp
  radio/src/pulses/modules_helpers.h
  radio/src/storage/yaml/CMakeLists.txt
  radio/src/storage/yaml/yaml_datastructs.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14_family.cpp
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/nv14/backlight_driver.cpp
  radio/src/targets/nv14/battery_driver.cpp
  radio/src/targets/nv14/battery_driver.h
  radio/src/targets/nv14/board.cpp
  radio/src/targets/nv14/board.h
  radio/src/targets/nv14/hal.h
  radio/src/targets/nv14/haptic_driver.cpp
  radio/src/targets/nv14/lcd_driver.cpp
  radio/src/targets/nv14/lcd_driver.h
  radio/src/targets/nv14/touch_driver.cpp
  radio/src/targets/nv14/touch_driver.h
  radio/src/targets/nv14/usb_descriptor.h
  radio/src/targets/pl18/CMakeLists.txt
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/telemetry/telemetry.cpp
  radio/src/telemetry/telemetry_sensors.cpp
  radio/src/translations.cpp
  radio/src/translations/bl_translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/ko.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
  tools/build-common.sh
Labels: house keeping 🧹
