Repository EdgeTX/edgetx, pull requests merged in 2025-05, with the labels that each got.

#6166 fix(taranis): battery voltage computation
  radio/src/boards/generic_stm32/battery_voltage.cpp
Labels: hardware support, bug/regression ↩️

#6174 fix(color): slow update of channel bars on outputs page.
  radio/src/gui/colorlcd/model/model_flightmodes.cpp
  radio/src/gui/colorlcd/model/model_logical_switches.cpp
  radio/src/gui/colorlcd/model/model_mixer_scripts.cpp
  radio/src/gui/colorlcd/model/model_outputs.cpp
  radio/src/gui/colorlcd/model/model_usbjoystick.cpp
  radio/src/gui/colorlcd/model/special_functions.cpp
  radio/src/gui/colorlcd/model/special_functions.h
  radio/src/gui/colorlcd/widgets/outputs.cpp
Labels: bug 🪲, color, UX-UI

#6180 chore: update ST USB middleware to 2.11.4
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CDC/Inc/usbd_cdc.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CompositeBuilder/Src/usbd_composite_builder.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Inc/usbd_customhid.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/CustomHID/Src/usbd_customhid_if_template.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_data.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_scsi.h
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c
  radio/src/thirdparty/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Inc/usbd_def.h
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_core.c
  radio/src/thirdparty/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
Labels: hardware support

#6171 feat(h7): RTC backup RAM
  radio/src/storage/rtc_backup.cpp
  radio/src/targets/common/arm/stm32/rtc_driver.cpp
  radio/src/targets/st16/CMakeLists.txt
Labels: hardware support

#6185 fix(actions): add UF2 to nightly releases
  .github/workflows/nightly.yml
Labels: bug 🪲, ci/cd

#6161 feat(radio): improve gimbal detection
  radio/src/boards/generic_stm32/analog_inputs.cpp
  radio/src/boards/generic_stm32/analog_inputs.h
  radio/src/cli.cpp
  radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp
  radio/src/targets/common/arm/stm32/flysky_gimbal_driver.h
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.h
  radio/src/targets/horus/board.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/pl18/board.cpp
  radio/src/targets/taranis/board.cpp
  radio/src/targets/taranis/hal.h
Labels: hardware support, house keeping 🧹

#6149 fix(h7): common drivers for H7 support
  radio/src/targets/common/arm/stm32/CMakeLists.txt
  radio/src/targets/common/arm/stm32/audio_dac_driver.cpp
  radio/src/targets/common/arm/stm32/rotary_encoder_driver.cpp
  radio/src/targets/common/arm/stm32/sdcard_spi.cpp
  radio/src/targets/common/arm/stm32/stm32_hal_ll.h
  radio/src/targets/common/arm/stm32/stm32_spi.cpp
  radio/src/targets/common/arm/stm32/stm32_spi.h
  radio/src/targets/common/arm/stm32/stm32_spi_h7.cpp
Labels: house keeping 🧹

#6190 fix(st16): PPM timer
  radio/src/targets/common/arm/stm32/h7/system_stm32h7xx.c
  radio/src/targets/st16/hal.h
Labels: bug 🪲

#6182 feat(color): add fixed color set to the color picker
  radio/src/gui/colorlcd/colors.cpp
  radio/src/gui/colorlcd/colors.h
  radio/src/gui/colorlcd/controls/color_editor.cpp
  radio/src/gui/colorlcd/controls/color_editor.h
  radio/src/gui/colorlcd/controls/color_picker.cpp
  radio/src/gui/colorlcd/radio/preview_window.cpp
  radio/src/gui/colorlcd/startup_shutdown.cpp
  radio/src/gui/colorlcd/themes/theme_manager.cpp
  radio/src/lua/api_colorlcd.cpp
  radio/src/lua/api_general.cpp
  radio/src/translations.cpp
  radio/src/translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/ko.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: enhancement ✨, color

#6193 fix(color): Lua LVGL object does not draw correctly when using a function
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: bug 🪲, color, lua-api

#6168 chore(radio): DAC driver cleanup
  radio/src/targets/common/arm/stm32/audio_dac_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/pl18/hal.h
  radio/src/targets/stm32h7s78-dk/hal.h
  radio/src/targets/taranis/board.cpp
  radio/src/targets/taranis/board.h
  radio/src/targets/taranis/hal.h
Labels: hardware support, house keeping 🧹

#6204 chore(color): remove legacy color definitions
  radio/src/lua/api_colorlcd.cpp
  radio/src/lua/api_general.cpp
  radio/src/thirdparty/Lua/src/linit.c
Labels: color, lua-api, house keeping 🧹

#6196 fix(simu): simulator shutdown
  radio/src/mixer_scheduler.cpp
  radio/src/os/sleep_native.cpp
  radio/src/os/task_freertos.h
  radio/src/os/task_pthread.cpp
  radio/src/os/task_pthread.h
  radio/src/os/timer_pthread.cpp
  radio/src/targets/simu/simpgmspace.cpp
  radio/src/targets/simu/simpgmspace.h
  radio/src/tasks.cpp
  radio/src/tasks/mixer_task.cpp
  radio/src/tasks/mixer_task.h
Labels: simulator, bug/regression ↩️

#6205 fix(cpn): 'variable length array' warning
  companion/src/firmwares/edgetx/yaml_modeldata.cpp
  radio/src/gui/colorlcd/lv_conf.h
Labels: companion, compilation, house keeping 🧹

#6206 fix(color): clipped second line for mixer adv edit header
  radio/src/gui/colorlcd/model/mixer_edit_adv.cpp
Labels: bug 🪲, color

#6212 feat(color): add 'menu' popup control to Lua API
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: color, lua-api

#6209 fix(bw): hidden line (multiplier) on trainer screen
  radio/src/gui/common/stdlcd/radio_trainer.cpp
Labels: UX-UI, B&W, bug/regression ↩️

#6179 fix(bw): drawPotsBars wrong draw pos if skipping entry
  radio/src/gui/128x64/view_main.cpp
Labels: bug 🪲, UX-UI, B&W

#6215 chore(bw): place screen inversion in a more logical place
  radio/src/edgetx.cpp
  radio/src/storage/sdcard_yaml.cpp
Labels: B&W, house keeping 🧹

#6223 fix: disable RTC_BACKUP_RAM for MT12
  radio/src/targets/taranis/CMakeLists.txt
Labels: bug 🪲

#6169 chore(radio): small board cleanup
  radio/src/boards/generic_stm32/module_ports.cpp
  radio/src/pulses/pulses.h
  radio/src/storage/storage.h
  radio/src/targets/common/arm/stm32/usb_driver.cpp
  radio/src/targets/horus/board.cpp
  radio/src/targets/horus/board.h
  radio/src/targets/taranis/board.cpp
Labels: hardware support, house keeping 🧹

#6170 feat(radio): static disk cache
  radio/src/boards/generic_stm32/linker/stm32h750_sdram/extra_sections.ld
  radio/src/boards/generic_stm32/linker/stm32h7rs_sdram/extra_sections.ld
  radio/src/disk_cache.cpp
  radio/src/disk_cache.h
  radio/src/targets/common/arm/stm32/h7/memory_sections.h
Labels: enhancement ✨, hardware support

#6225 chore(ci): drop all STM32F2 firmware builds
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  fw.json
Labels: ci/cd, house keeping 🧹

#6224 fix(color): Lvgl 'line' object in Lua script may crash
  radio/src/lua/lua_lvgl_widget.cpp
Labels: color, lua-api, bug/regression ↩️

#6229 fix(color): prevent crash, show error if Lua script uses a deleted LVGL object
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
  radio/src/lua/lua_widget.cpp
  radio/src/lua/lua_widget.h
Labels: color, lua-api

#6232 fix(simu): restarting timer_queue
  radio/src/os/task_pthread.cpp
  radio/src/os/timer_pthread.cpp
  radio/src/os/timer_pthread.h
  radio/src/os/timer_pthread_impl.h
Labels: simulator, bug/regression ↩️

#6237 fix(color): selecting S.PORT as telemetry for SBUS
  radio/src/gui/colorlcd/module/module_setup.cpp
Labels: bug 🪲, color

#6155 fix(v14): incorrect switch definition and add v12/v14 battery voltage sensing
  radio/src/targets/common/arm/stm32/CMakeLists.txt
  radio/src/targets/common/arm/stm32/csd203_sensor.cpp
  radio/src/targets/common/arm/stm32/csd203_sensor.h
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/targets/taranis/board.cpp
  radio/src/targets/taranis/hal.h
  radio/util/hw_defs/switch_config.py
Labels: bug/regression ↩️

#6243 feat(color): add a filter function to the Lua choice popup
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: enhancement ✨, color, lua-api

#6177 fix(color): load bootloader bitmaps in bootloaderInitScreen()
  radio/src/gui/colorlcd/bitmaps.cpp
  radio/src/gui/colorlcd/bitmaps.h
  radio/src/targets/horus/bootloader/boot_menu.cpp
  radio/src/targets/nv14/bootloader/boot_menu.cpp
  radio/src/targets/pl18/bootloader/boot_menu.cpp
  radio/src/targets/st16/bootloader/boot_menu.cpp
Labels: color, house keeping 🧹

#6242 chore(radio): Portuguese 🇵🇹 translation updates
  radio/src/translations/pt.h
Labels: translation

#6220 feat(cpn): Korean (ko_KR) translation support
  companion/src/CMakeLists.txt
  companion/src/translations.cpp
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_ko.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
Labels: translation

#6248 fix(color): incorrect array size calculation for grid lines in spectrum analyser.
  radio/src/gui/colorlcd/radio/radio_spectrum_analyser.cpp
Labels: bug 🪲, color

#6251 fix(color): widget zone size may be incorrect on startup.
  radio/src/gui/colorlcd/mainview/layout_factory_impl.cpp
  radio/src/gui/colorlcd/mainview/view_main_decoration.cpp
Labels: color, lua-api, bug/regression ↩️

#6250 fix(radio): value calculation when GV used as source in weight/offset changed from 2.10
  radio/src/mixer.cpp
Labels: bug 🪲, color, B&W

#6255 fix(t20v2): incorrect default transmitter battery calibration
  radio/src/targets/taranis/hal.h
Labels: bug 🪲, B&W, rn: warning

#6221 fix(f4): SPI DMA transfers
  radio/src/targets/common/arm/stm32/stm32_spi.cpp
Labels: bug/regression ↩️

#6270 fix(color): Lua LVGL line color not set correctly when 'pts' property is a function
  radio/src/lua/lua_lvgl_widget.cpp
Labels: color, lua-api, bug/regression ↩️

#6271 fix(color): output channel may not get focus when user taps on screen.
  radio/src/gui/colorlcd/controls/channel_bar.cpp
Labels: bug 🪲, color, UX-UI

#6262 feat(color): delay population of mix line button content so mixes tab loads faster
  radio/src/gui/colorlcd/libui/list_line_button.cpp
  radio/src/gui/colorlcd/model/model_mixes.cpp
Labels: enhancement ✨, color, UX-UI

#6272 fix(color): channel monitor bars are too wide and clip right edge.
  radio/src/gui/colorlcd/controls/channel_bar.cpp
Labels: color, UX-UI, bug/regression ↩️

#6276 fix(t18): normal switch off with one button
  radio/src/targets/common/arm/stm32/pwr_driver.cpp
Labels: bug/regression ↩️

#6260 chore(build): cleanup `INTERNAL_GPS` / `INTERNAL_GPS_BAUDRATE` options
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/pl18/CMakeLists.txt
  radio/src/targets/st16/CMakeLists.txt
Labels: house keeping 🧹

#6297 fix(lua): memory leak
  radio/src/lua/lua_widget.cpp
Labels: bug 🪲, house keeping 🧹

#6296 feat(color): reduce lag in scrolling main view when using model info widget
  radio/src/gui/colorlcd/libui/static.cpp
  radio/src/gui/colorlcd/libui/static.h
  radio/src/gui/colorlcd/mainview/topbar_impl.cpp
  radio/src/gui/colorlcd/mainview/view_main.cpp
  radio/src/gui/colorlcd/widgets/modelbmp.cpp
Labels: enhancement ✨, color, widget

#6283 fix(radio): verify PWM gimbal pulse length
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
Labels: hardware support, bug/regression ↩️

#6284 fix(radio): verify PWM gimbal pulse length
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
Labels: hardware support, bug/regression ↩️

#6189 chore(radio): unify the bootloader UI code.
  radio/src/CMakeLists.txt
  radio/src/bootloader/CMakeLists.txt
  radio/src/bootloader/bin_fw_files.cpp
  radio/src/bootloader/boot.cpp
  radio/src/bootloader/boot.h
  radio/src/bootloader/boot_dfu.cpp
  radio/src/bootloader/boot_menu.cpp
  radio/src/bootloader/boot_uf2.cpp
  radio/src/bootloader/firmware_files.h
  radio/src/bootloader/loadboot.cpp
  radio/src/fonts/Roboto/Roboto-Regular-BL.ttf
  radio/src/fonts/lvgl/lrg/lv_font_bl.c
  radio/src/fonts/lvgl/make_fonts.sh
  radio/src/fonts/lvgl/sml/lv_font_bl.c
  radio/src/fonts/lvgl/std/lv_font_bl.c
  radio/src/gui/colorlcd/boot_menu.cpp
  radio/src/gui/common/stdlcd/boot_menu.cpp
  radio/src/gui/common/stdlcd/fonts.cpp
  radio/src/gui/common/stdlcd/utf8.cpp
  radio/src/keys.cpp
  radio/src/targets/common/arm/stm32/bootloader/boot_dfu.cpp
  radio/src/targets/horus/CMakeLists.txt
  radio/src/targets/horus/bootloader/boot_menu.cpp
  radio/src/targets/nv14/CMakeLists.txt
  radio/src/targets/nv14/bootloader/boot_menu.cpp
  radio/src/targets/pl18/CMakeLists.txt
  radio/src/targets/pl18/bootloader/boot_menu.cpp
  radio/src/targets/simu/CMakeLists.txt
  radio/src/targets/st16/CMakeLists.txt
  radio/src/targets/st16/bootloader/boot_menu.cpp
  radio/src/targets/stm32h7s78-dk/CMakeLists.txt
  radio/src/targets/stm32h7s78-dk/bootloader/boot_menu.cpp
  radio/src/targets/taranis/CMakeLists.txt
  radio/src/translations/bl_translations.h
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/de.h
  radio/src/translations/en.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/ko.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: color, B&W, house keeping 🧹

#6288 fix(radio): potential crash if too many telemetry sensors discovered
  radio/src/gui/128x64/model_telemetry.cpp
  radio/src/gui/212x64/model_telemetry.cpp
  radio/src/gui/colorlcd/model/model_telemetry.cpp
  radio/src/gui/colorlcd/model/model_telemetry.h
  radio/src/telemetry/telemetry_sensors.cpp
  radio/src/telemetry/telemetry_sensors.h
Labels: bug 🪲, color, B&W

#6309 fix(radio): propagate DEBUG everywhere needed
  radio/src/FreeRTOSConfig.h
  radio/src/boards/generic_stm32/CMakeLists.txt
  radio/src/targets/common/arm/stm32/h7/CMakeLists.txt
Labels: compilation, house keeping 🧹

#6307 fix(st16): incomplete #6189 merge
  radio/src/bootloader/boot_dfu.cpp
Labels: bug/regression ↩️

#6282 feat(color): handle long press enter for pre-flight switch checks
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/212x64/model_setup.cpp
  radio/src/gui/colorlcd/libui/button_matrix.cpp
  radio/src/gui/colorlcd/model/preflight_checks.cpp
  radio/src/switches.cpp
  radio/src/switches.h
Labels: enhancement ✨, color, UX-UI

#6294 feat(color): additions/fixes for Lua LVGL API
  radio/src/gui/colorlcd/libui/choice.cpp
  radio/src/gui/colorlcd/libui/choice.h
  radio/src/gui/colorlcd/libui/filechoice.cpp
  radio/src/gui/colorlcd/libui/filechoice.h
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: color, lua-api

#6308 fix(bw): main view switch display may be incorrect
  radio/src/gui/128x64/view_main.cpp
Labels: UX-UI, B&W, bug/regression ↩️

#6327 feat(lua): add state & persistent properties to the logical switch API
  radio/src/lua/api_model.cpp
Labels: color, lua-api, B&W

#6329 fix(color): button text for some choice values may be incorrect
  radio/src/gui/colorlcd/libui/choice.h
Labels: color, UX-UI, bug/regression ↩️

#6300 fix(st16): external module DMA conflict
  radio/src/targets/st16/hal.h
Labels: bug 🪲

#6324 fix: clean led behaviour on shutdown
  radio/src/targets/horus/board.cpp
  radio/src/targets/taranis/board.cpp
Labels: bug 🪲

#6331 chore(gx12): clean double timer init
  radio/src/targets/taranis/gx12/bsp_io.cpp
Labels: house keeping 🧹

#6315 fix(v16): trim T5/T6 swapped
  radio/src/targets/horus/hal.h
Labels: bug 🪲
