Repository EdgeTX/edgetx, pull requests merged in 2025-08, with the labels that each got.

#6489 fix(bw): cannot select 'inc/dec' mode for Adjust SF on some radios
  radio/src/gui/128x64/model_special_functions.cpp
Labels: UX-UI, B&W, bug/regression ↩️

#6500 chore: fix MacOS Companion build on GH.
  radio/src/gui/colorlcd/libui/file_carosell.h
Labels: companion, compilation, house keeping 🧹

#6497 fix(cpn): simulator colours
  companion/src/simulation/simulatormainwindow.cpp
Labels: companion, simulator

#6522 fix(cpn): qcustomplot warning
  companion/src/thirdparty/qcustomplot/qcustomplot.cpp
Labels: companion, compilation

#6523 chore(cpn): stop compiler warnings
  companion/src/firmwares/generalsettings.cpp
  companion/src/firmwares/generalsettings.h
  companion/src/firmwares/modeldata.cpp
Labels: companion, compilation

#6533 chore: validate `fw.json` syntax and target order
  .github/workflows/actions.yml
  .github/workflows/validate_fw_json.yml
  fw.json
  tools/validate-json.py
Labels: ci/cd

#6538 fix(bootloader): resolve undefined BIDI references for Hebrew builds
  radio/src/CMakeLists.txt
  radio/src/gui/colorlcd/CMakeListsLVGL.txt
Labels: translation, compilation, bug/regression ↩️

#6542 fix: firmware size in UF2 bootloader after flashing
  radio/src/drivers/uf2_ghostfat.cpp
Labels: bug 🪲

#6548 fix(h7): no LTO for system_clock.c
  radio/src/targets/common/arm/stm32/h7/CMakeLists.txt
  radio/src/targets/st16/CMakeLists.txt
  radio/src/targets/stm32h7s78-dk/CMakeLists.txt
  radio/src/targets/tx15/CMakeLists.txt
Labels: bug/regression ↩️

#6545 fix(radio): microsecond timer
  radio/src/targets/common/arm/stm32/timers_driver.cpp
Labels: bug 🪲

#6546 chore(doc): CMake presets
  .github/workflows/actions.yml
  .gitignore
  CMakePresets.json
Labels: documentation, compilation

#6550 fix(radio): wider PWM gimbal boundaries
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
Labels: bug/regression ↩️

#6551 fix(radio): wider PWM gimbal boundaries
  radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
Labels: bug/regression ↩️

#6537 chore: add a helper tool for multi-lang building
  tools/build-multilang.sh
Labels: compilation

#6557 fix(simu): move fsLedXX to simu led driver
  radio/src/targets/simu/led_driver.cpp
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/tests/gtests.cpp
Labels: simulator, house keeping 🧹
