Repository EdgeTX/edgetx, pull requests merged in 2025-04, with the labels that each got.

#6005 fix(sim): libsims not unloading
  companion/src/helpers.cpp
  companion/src/simulation/simulator.h
  companion/src/simulator.cpp
Labels: bug 🪲, companion, simulator

#6034 fix(radio): channel outputs may jump when mix lines are inserted or deleted
  radio/src/mixes.cpp
Labels: bug 🪲, color, B&W

#6051 fix(color): widget option default values are not loaded on radio restart
  radio/src/gui/colorlcd/mainview/widget_settings.cpp
Labels: color, widget, lua, bug/regression ↩️

#6045 fix(radio): prevent dedicated RGB LEDs flickering
  radio/src/boards/generic_stm32/rgb_leds.cpp
  radio/src/gui/gui_common.cpp
  radio/src/lua/api_general.cpp
  radio/src/targets/taranis/gx12/bsp_io.cpp
  radio/src/targets/taranis/hal.h
  radio/src/targets/taranis/led_driver.cpp
Labels: bug 🪲

#6048 chore(x10): LED_GREEN_GPIO should not be configured
  radio/src/targets/horus/hal.h
  radio/src/targets/horus/led_driver.cpp
Labels: bug 🪲

#6062 feat(lua): add additional properties to the Lua Lvgl arc object.
  radio/src/gui/colorlcd/libui/etx_lv_theme.cpp
  radio/src/gui/colorlcd/libui/etx_lv_theme.h
  radio/src/gui/colorlcd/widgets/timer.cpp
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: enhancement ✨, color, lua-api

#6064 fix(radio): inconsistent display for sub trim in outputs, bold indicators for bw128
  radio/src/gui/128x64/model_outputs.cpp
  radio/src/gui/colorlcd/model/model_outputs.cpp
  radio/src/gui/colorlcd/model/output_edit.cpp
Labels: bug 🪲, color, UX-UI, B&W

#6060 fix(doc): describe more clearly availability of colorlcd Lua API functions
  radio/src/lua/api_colorlcd.cpp
Labels: documentation, lua-api, lua

#6063 fix(radio): missing translation strings
  radio/src/translations/cn.h
  radio/src/translations/cz.h
  radio/src/translations/da.h
  radio/src/translations/es.h
  radio/src/translations/fi.h
  radio/src/translations/fr.h
  radio/src/translations/he.h
  radio/src/translations/it.h
  radio/src/translations/jp.h
  radio/src/translations/nl.h
  radio/src/translations/pl.h
  radio/src/translations/pt.h
  radio/src/translations/ru.h
  radio/src/translations/se.h
  radio/src/translations/tw.h
  radio/src/translations/ua.h
Labels: translation, bug/regression ↩️

#6056 fix(color): scroll wheel direction is not intuitive when editing color bars
  radio/src/gui/colorlcd/controls/color_editor.cpp
  radio/src/gui/colorlcd/controls/color_picker.cpp
Labels: color, UX-UI

#6069 fix(bw): PAGE key events not passed to Lua telemetry scripts
  radio/src/gui/common/stdlcd/view_telemetry.cpp
  radio/src/gui/navigation/navigation.h
Labels: B&W, lua, bug/regression ↩️

#6070 chore: CMake 4.0 compatibility
  cmake/FetchMaxLibQt.cmake
  cmake/FetchMiniz.cmake
  cmake/FetchYamlCpp.cmake
  cmake/GenericDefinitions.cmake
  companion/src/CMakeLists.txt
Labels: compilation, house keeping 🧹

#6067 fix(radio): a 2POS switch connected to a 3POS socket may not behave as expected
  radio/src/switches.cpp
  radio/src/tests/mixer.cpp
Labels: bug 🪲, color, B&W

#6079 fix(color): bluetooth setup menu crashes when discovering devices
  radio/src/gui/colorlcd/libui/menu.cpp
Labels: color, UX-UI, bug/regression ↩️

#6077 fix(bw): switch display may overlap other elements if switches are disabled
  radio/src/gui/128x64/view_main.cpp
Labels: UX-UI, B&W, bug/regression ↩️

#6042 fix(cpn): valid mix name lengths, wizard translation context
  companion/src/translations/companion_cs.ts
  companion/src/translations/companion_da.ts
  companion/src/translations/companion_de.ts
  companion/src/translations/companion_en.ts
  companion/src/translations/companion_es.ts
  companion/src/translations/companion_fi.ts
  companion/src/translations/companion_fr.ts
  companion/src/translations/companion_he.ts
  companion/src/translations/companion_it.ts
  companion/src/translations/companion_ja.ts
  companion/src/translations/companion_nl.ts
  companion/src/translations/companion_pl.ts
  companion/src/translations/companion_pt.ts
  companion/src/translations/companion_ru.ts
  companion/src/translations/companion_sv.ts
  companion/src/translations/companion_zh_CN.ts
  companion/src/translations/companion_zh_TW.ts
  companion/src/wizarddata.cpp
Labels: bug 🪲, companion, translation

#6059 fix(simulator): libraries not unloading on closing simulator window
  companion/src/helpers.cpp
  radio/src/gui/colorlcd/libui/bitmapbuffer_fileio.cpp
Labels: bug 🪲, color, simulator

#6082 chore(cpn): disable all the warnings in the miniz header
  companion/src/storage/labeled.h
  companion/src/storage/minizinterface.h
Labels: companion, compilation

#6086 chore: SE translation updates
  companion/src/translations/companion_sv.ts
  radio/src/translations/se.h
Labels: translation

#6087 fix(color): widget 'Choice' option popup may show duplicate entries
  radio/src/lua/lua_widget_factory.cpp
Labels: color, widget, lua

#6084 chore(cpn): updated yerico icons for sd path read and write
  companion/src/themes/yerico/16/folder-tree-read.png
  companion/src/themes/yerico/16/folder-tree-write.png
  companion/src/themes/yerico/24/folder-tree-read.png
  companion/src/themes/yerico/24/folder-tree-write.png
  companion/src/themes/yerico/32/folder-tree-read.png
  companion/src/themes/yerico/32/folder-tree-write.png
  companion/src/themes/yerico/48/folder-tree-read.png
  companion/src/themes/yerico/48/folder-tree-write.png
Labels: enhancement ✨, companion, house keeping 🧹

#6089 feat: force gimbal detection on serial passthrough init
  radio/src/cli.cpp
  radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp
  radio/src/targets/common/arm/stm32/flysky_gimbal_driver.h
Labels: enhancement ✨, hardware support

#6090 fix(color): customisable switch name focus outline not cleared when editing using touch
  radio/src/gui/colorlcd/libui/textedit.cpp
Labels: bug 🪲, color, UX-UI, touch 👆

#6093 fix(bw): name display for custom switches may be incorrect.
  radio/src/gui/128x64/model_setup.cpp
Labels: bug 🪲, UX-UI, B&W

#6091 feat(lua): allow the filename for an image object to be set via a function.
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: enhancement ✨, color, lua-api

#6096 chore(ci): force use of mirrors for Qt for now
  .github/workflows/macosx_cpn.yml
  .github/workflows/win_cpn-64.yml
  tools/aqt-settings.ini
Labels: ci/cd, not-our-bug

#6100 fix(color): build-breaking typo in startup_shutdown.cpp
  radio/src/gui/colorlcd/startup_shutdown.cpp
Labels: color, compilation, bug/regression ↩️

#6105 fix: don't deinit non initialised Flysky gimbal interface
  radio/src/targets/common/arm/stm32/flysky_gimbal_driver.cpp
Labels: hardware support

#6098 feat(color): add file picker button to Lvgl Lua API
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/lua_lvgl_widget.cpp
  radio/src/lua/lua_lvgl_widget.h
Labels: enhancement ✨, color, lua-api

#6104 fix(color): QR code blocks touch events
  radio/src/gui/colorlcd/libui/static.cpp
  radio/src/lua/api_colorlcd_lvgl.cpp
  radio/src/lua/lua_lvgl_widget.cpp
Labels: bug 🪲, color, lua

#6107 fix(color): LVGL file picker may crash if 'get' function is not set in Lua
  radio/src/lua/lua_lvgl_widget.cpp
Labels: bug 🪲, color, lua-api

#6111 fix(bw): changing some model and radio settings does not update corresponding yaml file.
  radio/src/gui/128x64/model_setup.cpp
  radio/src/gui/common/stdlcd/menus.cpp
  radio/src/gui/common/stdlcd/radio_hardware.cpp
Labels: B&W, bug/regression ↩️, firmware

#6099 feat(color): increase max length for widget name
  companion/src/firmwares/customisation_data.h
  companion/src/modeledit/colorcustomscreens.cpp
  radio/src/datastructs.h
  radio/src/gui/colorlcd/mainview/widgets_container.h
  radio/src/storage/yaml/yaml_datastructs_f16.cpp
  radio/src/storage/yaml/yaml_datastructs_nb4p.cpp
  radio/src/storage/yaml/yaml_datastructs_nv14_family.cpp
  radio/src/storage/yaml/yaml_datastructs_st16.cpp
  radio/src/storage/yaml/yaml_datastructs_t15.cpp
  radio/src/storage/yaml/yaml_datastructs_x10.cpp
Labels: enhancement ✨, color, widget

#6120 fix(radio): half-duplex UART
  radio/src/boards/generic_stm32/module_ports.cpp
  radio/src/targets/common/arm/stm32/stm32_serial_driver.cpp
  radio/src/targets/common/arm/stm32/stm32_usart_driver.cpp
Labels: bug 🪲, hardware support

#6119 fix(build): PL18 yaml definition does not get updated by generate_yaml script.
  tools/generate-yaml.sh
Labels: compilation, bug/regression ↩️

#6108 fix(radio): WRONG PCB DETECTED - X10 with Touch Screen Mod
  radio/src/targets/common/arm/stm32/pwr_driver.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/taranis/hal.h
Labels: hardware support, bug/regression ↩️

#6126 fix(pl18): YAML datastructs not updated properly
  radio/src/storage/yaml/yaml_datastructs_pl18.cpp
Labels: bug/regression ↩️

#6131 fix(cpn): widget options may not be saved when models loaded from radio
  companion/src/firmwares/customisation_data.h
Labels: bug 🪲, companion

#6123 fix(bw212): german text for "Range" too long
  radio/src/translations/de.h
Labels: translation

#6129 feat(simu): add support for (RGB!!) customisable switches
  radio/src/simu.cpp
  radio/src/targets/simu/led_driver.cpp
  radio/src/targets/simu/switch_driver.cpp
Labels: color, simulator

#6132 fix(libsim): use different `__weak` syntax depending on target
  radio/src/targets/simu/led_driver.cpp
Labels: simulator, compilation, bug/regression ↩️

#6135 chore: allow for more libclang versions
  radio/util/find_clang.py
Labels: compilation

#6138 chore(simulator): fix build of simulator libraries
  radio/src/targets/simu/led_driver.cpp
  radio/src/targets/simu/opentxsimulator.cpp
Labels: compilation, bug/regression ↩️

#6141 chore(devcontainer): new devcontainer schema, graphics perms on linux
  .devcontainer/devcontainer.json
Labels: house keeping 🧹

#6142 chore(simulator): fix build of simulator libraries
  radio/src/hal/CMakeLists.txt
  radio/src/targets/simu/led_driver.cpp
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/tests/gtests.cpp
Labels: compilation, bug/regression ↩️

#6144 chore(cpn): libsimulator build fails when DEBUG=RTT.
  radio/src/CMakeLists.txt
Labels: bug 🪲, compilation

#6147 fix(x7access): internal module power
  radio/src/targets/taranis/hal.h
Labels: hardware support, bug/regression ↩️

#6150 fix(color): channel monitor 'inverted' icon overlaps channel bars.
  radio/src/gui/colorlcd/controls/channel_bar.cpp
  radio/src/gui/colorlcd/controls/channel_bar.h
Labels: color, UX-UI, bug/regression ↩️

#6143 chore: more dynamic llvm path search on linux
  radio/util/find_clang.py
Labels: compilation, house keeping 🧹

#6151 chore: remove unused files.
  radio/src/targets/st16/libopenui_config.h
  radio/src/targets/stm32h7s78-dk/libopenui_config.h
Labels: compilation, house keeping 🧹

#6152 fix: tlite vbat voltage
  radio/src/targets/taranis/board.h
Labels: bug/regression ↩️

#6154 chore: replace test images
  radio/src/tests/images/color/primitives_EN_320x480.png
  radio/src/tests/images/color/primitives_EN_480x272.png
  radio/src/tests/images/color/primitives_EN_480x320.png
  radio/src/tests/images/color/transparency_EN_320x480.png
  radio/src/tests/images/color/transparency_EN_480x272.png
  radio/src/tests/images/color/transparency_EN_480x320.png
Labels: unit tests 🧪

#6065 refactor(radio): unified battery and RTC voltage
  radio/src/boards/generic_stm32/CMakeLists.txt
  radio/src/boards/generic_stm32/battery_voltage.cpp
  radio/src/hal/adc_driver.cpp
  radio/src/hal/adc_driver.h
  radio/src/targets/common/arm/stm32/stm32_adc.cpp
  radio/src/targets/horus/csd203_sensor.cpp
  radio/src/targets/horus/hal.h
  radio/src/targets/nv14/hal.h
  radio/src/targets/pl18/hal.h
  radio/src/targets/simu/adc_driver.cpp
  radio/src/targets/simu/opentxsimulator.cpp
  radio/src/targets/simu/opentxsimulator.h
  radio/src/targets/taranis/board.h
Labels: house keeping 🧹

#6156 fix(ci): add missing fw build, correct v14 switch defs
  .github/workflows/actions.yml
  radio/util/build-firmware.py
  radio/util/fwoptions.py
  radio/util/hw_defs/switch_config.py
Labels: ci/cd, compilation, bug/regression ↩️, house keeping 🧹

#6157 fix(color): channel bars on outputs list not correct size if extended limits setting changed
  radio/src/gui/colorlcd/controls/channel_bar.cpp
  radio/src/gui/colorlcd/controls/channel_bar.h
Labels: bug 🪲, color, UX-UI

#6158 fix(horus): detection for Flysky Hall Gimbals not working
  radio/src/targets/horus/board.cpp
Labels: bug/regression ↩️

#6113 feat(color): value widget now shows voltage suffix for handset voltage
  radio/src/gui/colorlcd/widgets/value.cpp
Labels: color, widget

#6109 feat(color): allow long press of PAGE keys to navigate menus.
  radio/src/gui/colorlcd/libui/tabsgroup.cpp
  radio/src/gui/colorlcd/libui/tabsgroup.h
  radio/src/gui/colorlcd/libui/window.cpp
Labels: enhancement ✨, color, UX-UI

#6124 feat(color): show switch colors for customisable switches on diagnostic page
  radio/src/gui/colorlcd/radio/radio_diagcustswitches.cpp
  radio/src/hal/rgbleds.cpp
  radio/src/hal/rgbleds.h
  radio/src/switches.h
  radio/src/targets/simu/led_driver.cpp
  radio/src/targets/st16/led_driver.cpp
  radio/src/targets/taranis/led_driver.cpp
Labels: enhancement ✨, color, UX-UI
